export type Lang = "en" | "zh" | "id";

/* English is the source of truth. Missing keys in zh/id fall back to English. */
const en: Record<string, string> = {
  "ex.toClient": "Hi Aiko! I'll design 6 Instagram slides for your ceramics studio launch: 1080x1350 PNG, brand colors, delivered by Friday. Price $120.",
  "ex.fromClient": "Hi {name}! I need 20 product photos edited for my online store. Clean white background, at least 2000px, JPG. Can you deliver by Friday? Budget is $150.",
  "common.back": "Back",
  "common.next": "Next",

  "nav.dashboard": "Dashboard",
  "nav.orders": "Orders",
  "nav.newOrder": "Send an order",
  "nav.myPage": "My order page",
  "nav.profile": "Profile",
  "theme.label": "Theme",
  "theme.candy": "Candy",
  "theme.midnight": "Midnight",
  "theme.matcha": "Matcha",
  "me.menu.profile": "View profile",
  "me.menu.public": "My public page",
  "me.menu.paypal": "PayPal & payouts",
  "me.menu.signout": "Sign out",
  "me.toast.bye": "Signed out of the demo — see you soon! 👋",
  "me.title": "Your profile",
  "me.sub": "Your freelancer identity, preferences and payout account.",
  "me.since": "Member since 2024",
  "me.langs": "Speaks EN · ID · 中文",
  "me.edit": "Edit profile",
  "me.toast.edit": "PayPal connections are managed in the PayPal sandbox dashboard 🙂",
  "me.save": "Save",
  "me.cancel": "Cancel",
  "me.saved": "Profile saved — it follows you everywhere now.",
  "me.f.name": "Full name",
  "me.f.handle": "Handle (your link: /to/…)",
  "me.f.city": "City",
  "me.f.country": "Country code",
  "me.f.bio": "Bio",
  "me.f.tags": "Skills (comma separated)",
  "me.stats.done": "Orders completed",
  "me.stats.earned": "Total earned",
  "me.stats.rating": "Client rating",
  "me.prefs.theme": "Theme",
  "me.prefs.themeBody": "Pick a vibe — it saves automatically.",
  "me.prefs.lang": "Language",
  "me.prefs.langBody": "Language for menus, buttons and emails.",
  "me.paypal.title": "PayPal sandbox",
  "me.paypal.body": "Account used for escrow, releases and payouts.",
  "me.paypal.connected": "Connected",
  "me.paypal.manage": "Manage",
  "me.paypal.docs": "API docs",
  "me.signoutCard": "Sign out of this demo",
  "me.signoutBody": "Your language and theme stay saved on this device.",
  "tip.title": "Capi's tip",
  "tip.body": "You have {n} new requests. Clients who get a reply within 2 hours are 3× more likely to pay!",
  "top.search": "Search orders, clients…",
  "top.notifications": "Notifications",

  "status.request": "New request",
  "status.awaiting_payment": "Waiting for payment",
  "status.in_escrow": "Funds locked · working",
  "status.verifying": "AI is checking",
  "status.revision": "Needs a fix",
  "status.review": "Client reviewing",
  "status.paid": "Lunas! Paid",
  "status.declined": "Declined",

  "rail.paid": "{amount} landed in {name}'s PayPal 🎉",
  "rail.held": "{amount} is safely locked in escrow",
  "rail.declined": "Order declined · no money moved",
  "rail.notFunded": "Not funded yet · nothing at risk",
  "rail.client": "Client",
  "rail.escrow": "Lunas escrow",
  "rail.you": "You",
  "stamp.sub": "PAID IN FULL",

  "lp.nav.how": "How it works",
  "lp.nav.who": "Who it's for",
  "lp.nav.try": "Try the stamp",
  "lp.openApp": "Open app",
  "lp.kicker": "PayPal + AI escrow for freelancers",
  "lp.h1.a": "Get paid by clients abroad,",
  "lp.h1.b": "worry-free",
  "lp.h1.c": "and stamped.",
  "lp.sub": "Lunas turns a messy brief into a clear contract, locks the money with PayPal, and lets AI check the work. When everything's done, it's LUNAS — paid in full.",
  "lp.cta1": "Send your first order",
  "lp.cta2": "See a client's view",
  "lp.trust1": "PayPal-secured",
  "lp.trust2": "AI-verified work",
  "lp.trust3": "EN · 中文 · ID",
  "lp.scene.contract": "Work agreement",
  "lp.scene.job": "20 product photos",
  "lp.scene.c1": "Exactly 20 files",
  "lp.scene.c2": "JPG format",
  "lp.scene.c3": "Min. 2000px",
  "lp.scene.c4": "White background",
  "lp.scene.passed": "passed",

  "how.kicker": "4 tiny steps",
  "how.title": "How Lunas works",
  "how.1.t": "Describe it",
  "how.1.b": "Type the job like a chat message. AI turns it into checkable terms: file count, size, format, deadline.",
  "how.2.t": "Lock the money",
  "how.2.b": "The client pays with PayPal. Money waits safely in escrow. Nobody can run away with it.",
  "how.3.t": "AI checks the work",
  "how.3.b": "Upload the delivery. Our agent checks every criterion and asks for fixes before anyone argues.",
  "how.4.t": "Lunas!",
  "how.4.b": "Client approves (or stays silent for 72h) and the money lands in your PayPal. Stamp!",

  "who.f.k": "For freelancers",
  "who.f.t": "Never chase an invoice again",
  "who.f.1": "Get paid even if the client goes quiet",
  "who.f.2": "No more endless “one small change…”",
  "who.f.3": "Your own order page to share anywhere",
  "who.f.4": "Works with clients from any country",
  "who.c.k": "For clients",
  "who.c.t": "Pay upfront without the fear",
  "who.c.1": "Money is only released when the work matches",
  "who.c.2": "Clear terms written for you by AI",
  "who.c.3": "Pay with your PayPal account or card",
  "who.c.4": "Fair, fast refunds if something goes wrong",

  "try.kicker": "Go on, press it",
  "try.title": "The most satisfying button in fintech",
  "try.body": "In Indonesia, shops stamp a receipt “LUNAS” when it's paid in full. We kept the tradition, digitally.",
  "try.button": "Stamp it!",
  "try.again": "Stamp again",
  "try.receipt": "Payment receipt",
  "try.r.to": "Paid to",
  "try.r.from": "Paid by",
  "try.r.check": "Verification",
  "try.meaning": "“Lunas” (loo-nahs) is Indonesian for paid in full.",
  "cta.title": "Ready to get paid properly?",
  "cta.body": "Free in sandbox. Takes 2 minutes. Capi is waiting.",
  "foot.note": "Built for the PayPal AI Hackathon · runs on the PayPal sandbox",
  "marq.1": "Japan → United Kingdom",
  "marq.2": "United States → Indonesia",
  "marq.3": "Germany → Indonesia",
  "marq.4": "Singapore → Indonesia",
  "marq.5": "Indonesia → Australia",
  "marq.6": "Spain → Indonesia",
  "marq.7": "Netherlands → Indonesia",
  "marq.8": "South Korea → Indonesia",
  "marq.9": "Indonesia → Japan",
  "marq.10": "Canada → Indonesia",
  "cert.title": "Certificate of Completion",
  "cert.no": "Certificate No.",
  "cert.date": "Issued",
  "cert.verified": "Verified by Lunas AI · {n}/{n} criteria met",
  "cert.download": "Download certificate",
  "cert.hint": "High-res PNG, ready to frame",
  "cert.toast": "Certificate saved — frame it! 🖼️",

  "dash.hi": "Good morning, {name}!",
  "dash.summary": "You have {r} new requests and {w} orders waiting for you. Let's get stamping!",
  "dash.sendOrder": "Send order to a client",
  "dash.copyLink": "Copy my order link",
  "dash.capiSays": "You're doing great!",
  "dash.stat.held": "In escrow",
  "dash.stat.paid": "Paid out",
  "dash.stat.requests": "New requests",
  "dash.stat.release": "Avg. payout time",
  "dash.stat.releaseVal": "1.8 days",
  "dash.attention": "Needs your attention",
  "dash.seeAll": "See all",
  "dash.earnings": "Weekly earnings",
  "dash.activity": "Recent activity",
  "act.1": "Olivia approved “Etsy banner” · $75 paid",
  "act.2": "Mei Lin sent you a new request",
  "act.3": "AI found a grey background in IMG_014",
  "act.4": "James funded $150 into escrow",
  "time.min": "{n} min ago",
  "time.hour": "{n} h ago",
  "time.yesterday": "Yesterday",
  "order.due": "Due {date}",
  "toast.copied": "Link copied!",

  "orders.title": "Orders",
  "orders.sub": "Everything coming in and going out, in one happy place.",
  "orders.myPage": "My order page",
  "orders.new": "New order to client",
  "orders.tab.from": "From clients",
  "orders.tab.fromSub": "Clients asked you to do work",
  "orders.tab.to": "To clients",
  "orders.tab.toSub": "Orders you sent to clients",
  "orders.newBadge": "{n} new!",
  "filter.all": "All",
  "filter.action": "Needs action",
  "filter.escrow": "Active",
  "filter.review": "In review",
  "filter.paid": "Lunas",
  "orders.empty": "Nothing here yet",
  "orders.emptySub": "Try another filter, or send a new order.",
  "orders.share.t": "Want more orders from clients?",
  "orders.share.b": "Share your order page on Instagram, LinkedIn or WhatsApp. Clients describe the job, AI writes the contract.",
  "orders.share.preview": "Preview",
  "cta.review": "Review",
  "cta.remind": "Remind",
  "cta.deliver": "Deliver",
  "cta.view": "View",
  "cta.fix": "Fix it",
  "cta.receipt": "Receipt",

  "new.title": "Send an order to a client",
  "new.sub": "Write the job once. Lunas makes the contract and a PayPal payment link.",
  "new.s1": "Client",
  "new.s2": "The job",
  "new.s3": "Contract",
  "new.s4": "Send",
  "new.clientT": "Who is this for?",
  "new.clientB": "We'll email them a link to review and pay.",
  "new.clientName": "Client name",
  "new.clientEmail": "Client email",
  "new.clientCountry": "Country",
  "new.other": "Other — type it yourself",
  "new.otherPh": "Country name, e.g. Brazil",
  "new.currency": "Currency",
  "new.fillDemo": "Fill demo client",
  "new.jobT": "What will you deliver?",
  "new.jobB": "Write it like a message. Include numbers: how many, what size, what format, when.",
  "new.briefLabel": "Job description",
  "new.briefPh": "e.g. 6 Instagram slides, 1080x1350 PNG, brand colors, by Friday, $120",
  "new.useExample": "Use an example",
  "new.draftAI": "Draft contract with AI",
  "new.redraft": "Draft again",
  "new.aiHint": "AI turns your words into checkable criteria.",
  "new.thinking": "Capi is reading your brief…",
  "new.criteria": "Acceptance criteria",
  "new.aiVerified": "AI-verified",
  "new.agreement": "Work agreement",
  "new.orderTitle": "Order title",
  "new.draft": "Draft",
  "new.amount": "Price",
  "new.due": "Deadline",
  "new.window": "Client review window",
  "new.hours": "hours",
  "new.windowHint": "If the client doesn't respond within {h} hours, the money is released to you automatically.",
  "new.addCrit": "Add your own criterion…",
  "new.clientPays": "Client pays",
  "new.fee": "Lunas fee (2.5%, paid by client)",
  "new.youGet": "You receive",
  "new.send": "Create & send",
  "new.sentT": "Order sent!",
  "new.sentB": "We emailed {name} a link to review the contract and pay with PayPal. We'll ping you the moment the money is locked.",
  "new.copy": "Copy link",
  "new.email": "Email again",
  "new.previewT": "What your client sees",
  "new.from": "From",
  "new.previewProtect": "Protected by Lunas escrow · {h}h review",
  "new.goOrder": "Go to order",
  "new.another": "Create another",
  "pay.with": "Pay with",

  "tl.agree": "Agreement",
  "tl.fund": "Funded",
  "tl.work": "Delivery",
  "tl.verify": "AI check",
  "tl.lunas": "Lunas",
  "toast.accepted": "Accepted! Payment link sent.",
  "toast.funded": "Money locked in escrow!",
  "decl.t": "You declined this request",
  "decl.b": "The client was notified kindly. No money moved.",
  "decl.undo": "Undo",
  "od.briefFrom": "original brief",
  "od.window": "Review window",
  "od.auto": "auto-release",
  "req.t": "{name} wants to work with you!",
  "req.b": "AI already turned their brief into clear criteria. Accept, or suggest changes.",
  "req.accept": "Accept · {amount}",
  "req.counter": "Suggest changes",
  "req.decline": "Decline",
  "pay.t": "Waiting for the client to pay",
  "pay.b": "We sent {name} a PayPal payment link. Start working once the money is locked.",
  "pay.remind": "Send reminder",
  "demo.label": "Demo · simulate the client",
  "pay.processing": "Capturing in PayPal sandbox…",
  "pay.captured": "Captured · locked",
  "pay.simulate": "Client pays with",
  "pay.sandbox": "PayPal sandbox · pay with a test account",
  "pay.loading": "Loading PayPal sandbox…",
  "dl.t": "Time to deliver!",
  "dl.b": "Money is locked. Upload your files and let AI check them against the contract.",
  "dl.verT": "AI is checking your files…",
  "dl.verB": "Every criterion, one by one. No opinions, just the contract.",
  "dl.revT": "Almost there! One thing to fix",
  "dl.revB": "The money stays safely locked while you fix it.",
  "dl.drop": "Drop your files here",
  "dl.dropSub": "or click to upload · demo uses sample images",
  "dl.run": "Run AI check",
  "dl.agentSays": "Verification agent",
  "dl.agentMsg": "IMG_014 has a light-grey background (21% non-white pixels). Fix it and re-upload. Everything else is perfect!",
  "dl.reupload": "Re-upload fixed file",
  "rev.t": "All checks passed! Client is reviewing",
  "rev.b": "{name} can approve now. If they stay silent, you get paid automatically.",
  "rev.until": "until auto-release",
  "rev.safe": "Your money is protected",
  "rev.explain": "The client can only dispute with a reason linked to a criterion. Silence means approval.",
  "rev.simulate": "Client approves",
  "rev.releasing": "Releasing…",
  "paid.t": "LUNAS! You got paid",
  "paid.b": "{amount} was sent to your PayPal via Payouts.",
  "log.title": "Agent activity",
  "med.t": "Dispute desk · Mediator Agent",
  "med.b": "Unhappy with the delivery? Say why. The Mediator reads the contract evidence and rules on the escrow.",
  "med.chips": "Example claims",
  "med.chip.1": "3 slides don't match the brief colours, and the delivery was late.",
  "med.chip.2": "I never received the files, and it's already a week past the deadline.",
  "med.chip.3": "Only 14 of the 20 photos arrived; IMG_007 is blurry and unusable.",
  "med.chip.4": "Love it, great job — just one tiny typo on slide 2.",
  "med.ph": "e.g. Only 14 of the 20 photos arrived, and IMG_007 still has a grey background…",
  "med.ask": "Ask the Mediator",
  "med.thinking": "Reading the evidence…",
  "med.short": "Write a few words first — the Mediator needs a claim to rule on.",
  "med.verdict": "Mediator verdict",
  "med.dec.release": "Release to freelancer",
  "med.dec.refund_partial": "Partial refund",
  "med.dec.refund_full": "Full refund",
  "med.dec.escalate": "Escalate to a human",
  "med.amount": "{p}% of {amt} goes back to the client",
  "med.conf": "Confidence",
  "med.why": "Why",
  "med.signals": "Signals used",
  "med.next": "What happens next",
  "med.src.llm": "LLM ruling",
  "med.src.local": "local rule engine",
  "med.capture": "PayPal capture ID",
  "med.exec": "Execute refund on PayPal",
  "med.executing": "Calling Refunds API…",
  "med.simulate": "Run refund (demo)",
  "med.nocap": "No sandbox capture on record — this runs as a demo",
  "med.done": "Refund {status} · {id}",
  "med.err": "Refund failed",
  "med.voided": "Certificate voided — {p}% refunded to the client",
  "med.frozen": "Funds stay frozen until a human mediator rules",

  "pub.imSari": "I'm {name} →",
  "pub.bio": "Product photo editor & designer from Yogyakarta. I make online shops look delicious. 6 years, 86 happy clients, zero drama.",
  "pub.skill1": "Photo editing",
  "pub.skill2": "Social media design",
  "pub.skill3": "Logos",
  "pub.skill4": "Etsy & Shopify",
  "pub.rating": "rating",
  "pub.done": "orders done",
  "pub.release": "avg. delivery",
  "pub.protectT": "You're protected by Lunas",
  "pub.protectB": "Your payment is held in escrow and only released when the work matches the contract.",
  "pub.kicker": "Order request",
  "pub.title": "Hire {name} in 2 minutes",
  "pub.sub": "Describe what you need. AI turns it into a clear contract you can both trust.",
  "pub.yourName": "Your name",
  "pub.yourEmail": "Your email",
  "pub.briefPh": "e.g. I need 20 product photos edited, white background, JPG, by Friday. Budget $150.",
  "pub.budget": "Budget (USD)",
  "pub.send": "Send request",
  "pub.noPayYet": "You won't pay anything yet. You'll pay with PayPal only after {name} accepts.",
  "pub.sentT": "Request sent!",
  "pub.sentB": "{name} usually replies within a few hours. We'll email {email} when she accepts.",
  "pub.next1": "{name} reviews your request & contract",
  "pub.next2": "You pay {amount} with PayPal into escrow",
  "pub.next3": "AI checks the work, then you approve. Lunas!",
  "pub.seeAsSari": "See it as {name}",
  "pub.another": "Send another",
  /* ---------- sign-in & identity (PayPal sandbox + guest) ---------- */
  "lp.signin": "Sign in",
  "me.menu.signin": "Log in with PayPal",
  "me.menu.connected": "PayPal account connected",
  "me.signed.pp": "Signed in with PayPal (sandbox)",
  "me.toast.welcome": "Signed in as {name} — fill in your profile!",
  "me.id.pp": "You're signed in with PayPal (sandbox)",
  "me.id.ppBody": "Connected as {email}. This profile belongs to that PayPal account — every field below is yours to edit.",
  "me.id.account": "PayPal account ID:",
  "me.id.guest": "You're browsing as a guest",
  "me.id.guestBody": "This is the shared demo profile ({name}, {city}). Log in with PayPal to make the profile your own.",
  "me.paypal.notConnected": "Not connected",
  "me.paypal.bodyLive": "Payouts from this profile go to the PayPal account you signed in with.",
  "me.paypal.bodyGuest": "Sign in with a PayPal sandbox account to connect payouts to your own account.",
  "signin.kicker": "Sandbox mode",
  "signin.title": "How do you want to use Lunas?",
  "signin.sub": "Every flow works either way. Log in with PayPal to get a profile of your own, or jump straight in as the shared guest demo.",
  "signin.home": "Back to site",
  "signin.pp.badge": "Recommended",
  "signin.pp.kind": "PayPal Identity API · sandbox",
  "signin.pp.title": "Log in with PayPal",
  "signin.pp.body": "Use a PayPal sandbox personal account. We only receive what the Identity API shares — your name, email and PayPal account ID. No password ever reaches us.",
  "signin.pp.li1": "The profile is yours: edit name, city, bio and skills",
  "signin.pp.li2": "Your PayPal account ID becomes the payout receiver",
  "signin.pp.li3": "Sign out really ends the session",
  "signin.pp.cta": "Continue with PayPal",
  "signin.pp.again": "Switch PayPal account",
  "signin.pp.off": "PayPal sign-in is not configured on this deployment — guest mode still works.",
  "signin.guest.badge": "No account needed",
  "signin.guest.kind": "Guest mode",
  "signin.guest.title": "Continue as a guest",
  "signin.guest.body": "Try the shared demo profile of {name} in {city} and use every flow right away — orders, escrow, delivery, release.",
  "signin.guest.li1": "Full access to the app, no sign-up",
  "signin.guest.li2": "Edit the profile like any user would",
  "signin.guest.li3": "Nothing is sent anywhere; it stays in this browser",
  "signin.guest.cta": "Open the app as a guest",
  "signin.note": "Testing this project for the hackathon? The PayPal sandbox tester account (email + password) is listed in the repository README. Payments are sandbox-only — no real money moves.",
  "signin.error.title": "We couldn't sign you in",
  "signin.error.paypal_not_configured": "PayPal sign-in isn't configured on this deployment. Guest mode still works.",
  "signin.error.cancelled": "You cancelled on PayPal's side.",
  "signin.error.bad_state": "The sign-in link expired. Please try again.",
  "signin.error.no_code": "PayPal didn't return an authorization code.",
  "signin.error.generic": "PayPal returned an error. Please try again, or continue as a guest.",
  "me.id.fillCity": "add your city",
  /* ---------- profile photo, links & portfolio ---------- */
  "nav.portfolio": "Portfolio",
  "me.f.photo": "Profile photo",
  "me.photo.upload": "Upload photo",
  "me.photo.busy": "Processing…",
  "me.photo.remove": "Remove",
  "me.photo.hint": "A square image works best. It is resized to 512px and stays in this browser.",
  "me.photo.ready": "Photo ready — press Save to keep it.",
  "me.photo.err": "That file could not be read as an image.",
  "me.f.links": "Links",
  "me.f.x": "X (Twitter)",
  "me.f.linkedin": "LinkedIn",
  "me.f.instagram": "Instagram",
  "me.f.website": "Website",
  "me.f.portfolio": "Portfolio",
  "me.portfolio.add": "Add item",
  "me.portfolio.title": "Project title",
  "me.portfolio.url": "Portfolio link",
  "me.portfolio.remove": "Remove item",
  "me.portfolio.hint": "Up to 6 items — they show on your public page so clients can see your work.",
  "me.links.title": "Portfolio & links",
  "me.links.body": "This is what clients see on your public page.",
  "me.links.open": "Open",
  "me.links.empty": "No portfolio links yet — add a few so clients can see your work.",
  "pub.portfolio": "Portfolio",

  /* ---------- publishing the profile ---------- */
  "me.saved.publishing": "Saving…",
  "me.saved.published": "Saved & published — clients can see your page now.",
  "me.saved.localOnly": "Saved on this device. Server storage is not configured yet.",
  "me.saved.handleTaken": "That handle is already taken — pick another one.",
  "me.saved.failed": "Saved here, but publishing failed. Try again.",
  "me.publish.on": "Published — clients see this at /to/{handle}",
  "me.publish.off": "Not published yet — press Save to publish it",
  "me.publish.guest": "Only on this device — log in with PayPal to publish",
  "me.saved.tableMissing": "Saved on this device. The Supabase table is missing — run the setup SQL once.",
  /* ---------- masking account details ---------- */
  "me.reveal": "Show details",
  "me.hide": "Hide details",
  "me.mask.hint": "Account details are hidden so they don't show up in screen recordings.",

  /* ---------- insights (AG Studio) ---------- */
  "nav.insights": "Insights",
  "ins.title": "Your money, in one place",
  "ins.sub": "Every escrow order, payout and agent run — as a dashboard you can reshape yourself.",
  "ins.kpi.escrow": "In escrow right now",
  "ins.kpi.released": "Paid out to you",
  "ins.kpi.days": "Avg. days to payout",
  "ins.kpi.countries": "Client countries",
  "ins.studio.t": "Dashboard",
  "ins.studio.b": "Drag a field from the left to build a widget, or click a chart to cross-filter the rest. Your layout stays in this browser.",
  "ins.data.t": "Where this data comes from",
  "ins.data.b": "Orders come from Lunas; money events are the PayPal calls behind them (Orders v2 capture, Payouts v1 release, Payments v1 refund, fees); agent runs are the contract, verification and mediation calls.",
  "ins.engine": "AI verified",
  "ins.reset": "Reset layout",
  "ins.loading": "Loading the dashboard…",
  "ins.licensed": "AG Studio Pro (hackathon trial, evaluation only)",

};

const zh: Record<string, string> = {
  "ex.toClient": "你好 Aiko！我会为你的陶瓷工作室新品发布设计 6 张 Instagram 图：1080x1350 PNG，品牌色，周五前交付。价格 $120。",
  "ex.fromClient": "你好 {name}！我需要修 20 张产品照片，用于我的网店。纯白背景，至少 2000px，JPG 格式。周五前能交吗？预算 $150。",
  "common.back": "返回",
  "common.next": "下一步",

  "nav.dashboard": "概览",
  "nav.orders": "订单",
  "nav.newOrder": "发送订单",
  "nav.myPage": "我的接单页",
  "nav.profile": "个人资料",
  "theme.label": "主题",
  "theme.candy": "糖果",
  "theme.midnight": "午夜",
  "theme.matcha": "抹茶",
  "me.menu.profile": "查看资料",
  "me.menu.public": "我的公开页",
  "me.menu.paypal": "PayPal 与收款",
  "me.menu.signout": "退出登录",
  "me.toast.bye": "已退出演示 — 再见！👋",
  "me.title": "你的资料",
  "me.sub": "你的自由职业身份、偏好与收款账户。",
  "me.since": "2024 年加入",
  "me.langs": "语言 EN · ID · 中文",
  "me.edit": "编辑资料",
  "me.toast.edit": "PayPal 连接在 PayPal 沙盒仪表板中管理 🙂",
  "me.save": "保存",
  "me.cancel": "取消",
  "me.saved": "资料已保存 — 现在它会跟着你到处走。",
  "me.f.name": "全名",
  "me.f.handle": "用户名（你的链接：/to/…）",
  "me.f.city": "城市",
  "me.f.country": "国家代码",
  "me.f.bio": "简介",
  "me.f.tags": "技能（用逗号分隔）",
  "me.stats.done": "已完成订单",
  "me.stats.earned": "累计收入",
  "me.stats.rating": "客户评分",
  "me.prefs.theme": "主题",
  "me.prefs.themeBody": "选一个风格，自动保存。",
  "me.prefs.lang": "语言",
  "me.prefs.langBody": "菜单、按钮与邮件使用的语言。",
  "me.paypal.title": "PayPal 沙盒",
  "me.paypal.body": "用于托管、放款与收款的账户。",
  "me.paypal.connected": "已连接",
  "me.paypal.manage": "管理",
  "me.paypal.docs": "API 文档",
  "me.signoutCard": "退出此演示",
  "me.signoutBody": "语言与主题仍会保存在此设备上。",
  "tip.title": "Capi 小贴士",
  "tip.body": "你有 {n} 个新请求。2 小时内回复的客户，付款概率高 3 倍哦！",
  "top.search": "搜索订单、客户…",
  "top.notifications": "通知",

  "status.request": "新请求",
  "status.awaiting_payment": "等待付款",
  "status.in_escrow": "资金已锁定 · 进行中",
  "status.verifying": "AI 检查中",
  "status.revision": "需要修改",
  "status.review": "客户审核中",
  "status.paid": "Lunas！已付清",
  "status.declined": "已拒绝",

  "rail.paid": "{amount} 已到账 {name} 的 PayPal 🎉",
  "rail.held": "{amount} 已安全锁定在托管中",
  "rail.declined": "订单已拒绝 · 资金未变动",
  "rail.notFunded": "尚未付款 · 没有任何风险",
  "rail.client": "客户",
  "rail.escrow": "Lunas 托管",
  "rail.you": "你",
  "stamp.sub": "已全额付清",

  "lp.nav.how": "如何运作",
  "lp.nav.who": "适合谁",
  "lp.nav.try": "试试盖章",
  "lp.openApp": "打开应用",
  "lp.kicker": "为自由职业者打造的 PayPal + AI 托管",
  "lp.h1.a": "收海外客户的钱，",
  "lp.h1.b": "安心无忧",
  "lp.h1.c": "一章搞定。",
  "lp.sub": "Lunas 把模糊的需求变成清晰的合同，用 PayPal 锁定资金，再让 AI 检查交付成果。一切完成后，盖上 LUNAS —— 全额付清。",
  "lp.cta1": "发送第一笔订单",
  "lp.cta2": "查看客户视角",
  "lp.trust1": "PayPal 安全保障",
  "lp.trust2": "AI 验收作品",
  "lp.trust3": "EN · 中文 · ID",
  "lp.scene.contract": "工作协议",
  "lp.scene.job": "20 张产品照片",
  "lp.scene.c1": "正好 20 个文件",
  "lp.scene.c2": "JPG 格式",
  "lp.scene.c3": "至少 2000px",
  "lp.scene.c4": "纯白背景",
  "lp.scene.passed": "通过",

  "how.kicker": "简单 4 步",
  "how.title": "Lunas 如何运作",
  "how.1.t": "描述需求",
  "how.1.b": "像发消息一样描述工作。AI 会把它变成可检查的条款：文件数量、尺寸、格式、截止日期。",
  "how.2.t": "锁定资金",
  "how.2.b": "客户用 PayPal 付款，资金安全地保存在托管中，谁也拿不走。",
  "how.3.t": "AI 检查作品",
  "how.3.b": "上传交付文件，AI 代理逐条检查标准，在争执发生前就提出修改。",
  "how.4.t": "Lunas！",
  "how.4.b": "客户确认（或 72 小时内未回应），钱就会到你的 PayPal。盖章！",

  "who.f.k": "给自由职业者",
  "who.f.t": "再也不用追着要钱",
  "who.f.1": "客户失联也能收到钱",
  "who.f.2": "告别没完没了的“再改一点点…”",
  "who.f.3": "专属接单页，随处分享",
  "who.f.4": "支持任何国家的客户",
  "who.c.k": "给客户",
  "who.c.t": "放心预付，不再担心",
  "who.c.1": "作品符合要求才会放款",
  "who.c.2": "AI 帮你写好清晰的条款",
  "who.c.3": "用 PayPal 账户或银行卡支付",
  "who.c.4": "出问题时公平、快速退款",

  "try.kicker": "来，按一下",
  "try.title": "金融科技里最解压的按钮",
  "try.body": "在印尼，商店会在付清的收据上盖“LUNAS”章。我们把这个传统搬到了线上。",
  "try.button": "盖章！",
  "try.again": "再盖一次",
  "try.receipt": "付款收据",
  "try.r.to": "收款人",
  "try.r.from": "付款人",
  "try.r.check": "验收",
  "try.meaning": "“Lunas”（鲁-纳斯）在印尼语里意思是“全额付清”。",
  "cta.title": "准备好安心收款了吗？",
  "cta.body": "沙盒环境免费使用，2 分钟上手。Capi 在等你。",
  "foot.note": "为 PayPal AI 黑客松打造 · 运行于 PayPal 沙盒",
  "marq.1": "日本 → 英国",
  "marq.2": "美国 → 印度尼西亚",
  "marq.3": "德国 → 印度尼西亚",
  "marq.4": "新加坡 → 印度尼西亚",
  "marq.5": "印度尼西亚 → 澳大利亚",
  "marq.6": "西班牙 → 印度尼西亚",
  "marq.7": "荷兰 → 印度尼西亚",
  "marq.8": "韩国 → 印度尼西亚",
  "marq.9": "印度尼西亚 → 日本",
  "marq.10": "加拿大 → 印度尼西亚",
  "cert.title": "完成证书",
  "cert.no": "证书编号",
  "cert.date": "签发日期",
  "cert.verified": "Lunas AI 已验证 · {n}/{n} 项标准通过",
  "cert.download": "下载证书",
  "cert.hint": "高清 PNG，可直接裱框",
  "cert.toast": "证书已保存 — 裱起来吧！🖼️",

  "dash.hi": "早上好，{name}！",
  "dash.summary": "你有 {r} 个新请求和 {w} 个待处理订单。一起去盖章吧！",
  "dash.sendOrder": "给客户发订单",
  "dash.copyLink": "复制接单链接",
  "dash.capiSays": "你做得超棒！",
  "dash.stat.held": "托管中",
  "dash.stat.paid": "已到账",
  "dash.stat.requests": "新请求",
  "dash.stat.release": "平均到账时间",
  "dash.stat.releaseVal": "1.8 天",
  "dash.attention": "需要你处理",
  "dash.seeAll": "查看全部",
  "dash.earnings": "每周收入",
  "dash.activity": "最新动态",
  "act.1": "Olivia 确认了“Etsy 横幅” · 已到账 $75",
  "act.2": "Mei Lin 给你发了新请求",
  "act.3": "AI 发现 IMG_014 背景偏灰",
  "act.4": "James 已向托管支付 $150",
  "time.min": "{n} 分钟前",
  "time.hour": "{n} 小时前",
  "time.yesterday": "昨天",
  "order.due": "截止 {date}",
  "toast.copied": "链接已复制！",

  "orders.title": "订单",
  "orders.sub": "收到的和发出的订单，都在这里。",
  "orders.myPage": "我的接单页",
  "orders.new": "给客户发新订单",
  "orders.tab.from": "来自客户",
  "orders.tab.fromSub": "客户请你做的工作",
  "orders.tab.to": "发给客户",
  "orders.tab.toSub": "你发给客户的订单",
  "orders.newBadge": "{n} 个新的！",
  "filter.all": "全部",
  "filter.action": "待处理",
  "filter.escrow": "进行中",
  "filter.review": "审核中",
  "filter.paid": "已付清",
  "orders.empty": "这里还没有内容",
  "orders.emptySub": "换个筛选条件，或者发一个新订单。",
  "orders.share.t": "想接更多客户订单？",
  "orders.share.b": "把接单页分享到 Instagram、LinkedIn 或 WhatsApp。客户描述需求，AI 自动写合同。",
  "orders.share.preview": "预览",
  "cta.review": "查看",
  "cta.remind": "提醒",
  "cta.deliver": "交付",
  "cta.view": "查看",
  "cta.fix": "去修改",
  "cta.receipt": "收据",

  "new.title": "给客户发送订单",
  "new.sub": "写一次需求，Lunas 自动生成合同和 PayPal 付款链接。",
  "new.s1": "客户",
  "new.s2": "工作内容",
  "new.s3": "合同",
  "new.s4": "发送",
  "new.clientT": "这个订单发给谁？",
  "new.clientB": "我们会给对方发邮件，附上查看和付款的链接。",
  "new.clientName": "客户姓名",
  "new.clientEmail": "客户邮箱",
  "new.clientCountry": "国家",
  "new.other": "其他 — 自己输入",
  "new.otherPh": "国家名称，例如：巴西",
  "new.currency": "币种",
  "new.fillDemo": "填入示例客户",
  "new.jobT": "你要交付什么？",
  "new.jobB": "像发消息一样写。记得写上数字：数量、尺寸、格式、时间。",
  "new.briefLabel": "工作描述",
  "new.briefPh": "例如：6 张 Instagram 图，1080x1350 PNG，品牌色，周五前，$120",
  "new.useExample": "使用示例",
  "new.draftAI": "用 AI 起草合同",
  "new.redraft": "重新起草",
  "new.aiHint": "AI 会把你的描述变成可检查的标准。",
  "new.thinking": "Capi 正在阅读你的需求…",
  "new.criteria": "验收标准",
  "new.aiVerified": "AI 验收",
  "new.agreement": "工作协议",
  "new.orderTitle": "订单标题",
  "new.draft": "草稿",
  "new.amount": "价格",
  "new.due": "截止日期",
  "new.window": "客户审核期",
  "new.hours": "小时",
  "new.windowHint": "如果客户 {h} 小时内没有回应，款项将自动打给你。",
  "new.addCrit": "添加自定义标准…",
  "new.clientPays": "客户支付",
  "new.fee": "Lunas 服务费（2.5%，由客户支付）",
  "new.youGet": "你将收到",
  "new.send": "创建并发送",
  "new.sentT": "订单已发送！",
  "new.sentB": "我们已给 {name} 发送邮件，对方可查看合同并用 PayPal 付款。资金锁定后会第一时间通知你。",
  "new.copy": "复制链接",
  "new.email": "再发一次邮件",
  "new.previewT": "客户看到的样子",
  "new.from": "来自",
  "new.previewProtect": "受 Lunas 托管保护 · {h} 小时审核期",
  "new.goOrder": "查看订单",
  "new.another": "再建一个",
  "pay.with": "使用",

  "tl.agree": "协议",
  "tl.fund": "已付款",
  "tl.work": "交付",
  "tl.verify": "AI 检查",
  "tl.lunas": "付清",
  "toast.accepted": "已接受！付款链接已发送。",
  "toast.funded": "资金已锁定在托管中！",
  "decl.t": "你拒绝了这个请求",
  "decl.b": "我们已礼貌地通知客户，资金未变动。",
  "decl.undo": "撤销",
  "od.briefFrom": "原始需求",
  "od.window": "审核期",
  "od.auto": "自动放款",
  "req.t": "{name} 想和你合作！",
  "req.b": "AI 已把需求整理成清晰的标准。接受，或者提出修改。",
  "req.accept": "接受 · {amount}",
  "req.counter": "提出修改",
  "req.decline": "拒绝",
  "pay.t": "等待客户付款",
  "pay.b": "我们已给 {name} 发送 PayPal 付款链接。资金锁定后再开工。",
  "pay.remind": "发送提醒",
  "demo.label": "演示 · 模拟客户操作",
  "pay.processing": "正在 PayPal 沙盒中扣款…",
  "pay.captured": "已扣款 · 已锁定",
  "pay.simulate": "客户付款，使用",
  "pay.sandbox": "PayPal 沙盒 · 用测试账号支付",
  "pay.loading": "正在加载 PayPal 沙盒…",
  "dl.t": "该交付啦！",
  "dl.b": "资金已锁定。上传文件，让 AI 对照合同检查。",
  "dl.verT": "AI 正在检查你的文件…",
  "dl.verB": "逐条检查，不看主观意见，只看合同。",
  "dl.revT": "快好了！还有一处要改",
  "dl.revB": "修改期间，资金仍安全锁定。",
  "dl.drop": "把文件拖到这里",
  "dl.dropSub": "或点击上传 · 演示使用示例图片",
  "dl.run": "运行 AI 检查",
  "dl.agentSays": "验收代理",
  "dl.agentMsg": "IMG_014 的背景是浅灰色（21% 非白色像素）。修改后重新上传即可，其他都很完美！",
  "dl.reupload": "重新上传修改后的文件",
  "rev.t": "全部通过！客户审核中",
  "rev.b": "{name} 现在可以确认。如果对方不回应，你也会自动收到款项。",
  "rev.until": "后自动放款",
  "rev.safe": "你的钱受保护",
  "rev.explain": "客户只能基于某条标准提出异议。不回应即视为确认。",
  "rev.simulate": "客户确认",
  "rev.releasing": "放款中…",
  "paid.t": "LUNAS！钱到账了",
  "paid.b": "{amount} 已通过 Payouts 发送到你的 PayPal。",
  "log.title": "代理动态",
  "med.t": "调解台 · 调解代理",
  "med.b": "对交付不满意？说明理由。调解代理会读取合同证据，并裁定托管资金的归属。",
  "med.chips": "示例申诉",
  "med.chip.1": "有 3 张幻灯片的颜色不符合需求，而且交付延误了。",
  "med.chip.2": "我根本没有收到文件，而且已经逾期一周了。",
  "med.chip.3": "20 张照片只到了 14 张，IMG_007 很模糊，没法用。",
  "med.chip.4": "整体很好，很满意 — 只有第 2 页有个小错别字。",
  "med.ph": "例如：20 张照片只收到 14 张，IMG_007 的背景还是灰的……",
  "med.ask": "请调解代理裁定",
  "med.thinking": "正在读取证据……",
  "med.short": "请先写几句话 — 调解需要申诉内容。",
  "med.verdict": "调解结果",
  "med.dec.release": "放款给自由职业者",
  "med.dec.refund_partial": "部分退款",
  "med.dec.refund_full": "全额退款",
  "med.dec.escalate": "移交人工处理",
  "med.amount": "{amt} 中的 {p}% 退还客户",
  "med.conf": "置信度",
  "med.why": "理由",
  "med.signals": "使用的信号",
  "med.next": "接下来会发生什么",
  "med.src.llm": "大模型裁定",
  "med.src.local": "本地规则引擎",
  "med.capture": "PayPal capture ID",
  "med.exec": "在 PayPal 执行退款",
  "med.executing": "正在调用退款接口……",
  "med.simulate": "执行退款（演示）",
  "med.nocap": "没有沙盒 capture 记录 — 以演示模式运行",
  "med.done": "退款 {status} · {id}",
  "med.err": "退款失败",
  "med.voided": "证书已作废 — 已退还客户 {p}%",
  "med.frozen": "在人工调解裁定前，资金保持冻结",

  "pub.imSari": "我是 {name} →",
  "pub.bio": "来自日惹的产品修图师和设计师，让网店看起来更诱人。6 年经验，86 位满意客户，零纠纷。",
  "pub.skill1": "照片修图",
  "pub.skill2": "社交媒体设计",
  "pub.skill3": "Logo",
  "pub.skill4": "Etsy 和 Shopify",
  "pub.rating": "评分",
  "pub.done": "已完成订单",
  "pub.release": "平均交付",
  "pub.protectT": "你受 Lunas 保护",
  "pub.protectB": "你的付款保存在托管中，只有作品符合合同才会放款。",
  "pub.kicker": "订单请求",
  "pub.title": "2 分钟雇佣 {name}",
  "pub.sub": "描述你的需求，AI 会把它变成双方都信任的清晰合同。",
  "pub.yourName": "你的名字",
  "pub.yourEmail": "你的邮箱",
  "pub.briefPh": "例如：需要修 20 张产品图，白底，JPG，周五前。预算 $150。",
  "pub.budget": "预算（美元）",
  "pub.send": "发送请求",
  "pub.noPayYet": "现在不用付款。{name} 接受后，再用 PayPal 付款。",
  "pub.sentT": "请求已发送！",
  "pub.sentB": "{name} 通常几小时内回复。她接受后，我们会发邮件到 {email}。",
  "pub.next1": "{name} 查看你的请求和合同",
  "pub.next2": "你用 PayPal 支付 {amount} 到托管",
  "pub.next3": "AI 检查作品，你确认。Lunas！",
  "pub.seeAsSari": "以 {name} 的视角查看",
  "pub.another": "再发一个",
  /* ---------- 登录与身份（PayPal 沙盒 + 访客） ---------- */
  "lp.signin": "登录",
  "me.menu.signin": "使用 PayPal 登录",
  "me.menu.connected": "PayPal 账户已连接",
  "me.signed.pp": "已使用 PayPal 登录（沙盒）",
  "me.toast.welcome": "已以 {name} 的身份登录 — 来完善你的资料吧！",
  "me.id.pp": "你已使用 PayPal 登录（沙盒）",
  "me.id.ppBody": "已连接 {email}。此资料属于该 PayPal 账户 —— 下面每个字段都可以编辑。",
  "me.id.account": "PayPal 账户 ID：",
  "me.id.guest": "你正在以访客身份浏览",
  "me.id.guestBody": "这是共享的演示资料（{name}，{city}）。使用 PayPal 登录即可把它变成你自己的。",
  "me.paypal.notConnected": "未连接",
  "me.paypal.bodyLive": "此资料的收款将进入你登录所用的 PayPal 账户。",
  "me.paypal.bodyGuest": "使用 PayPal 沙盒账户登录，即可把收款连接到自己的账户。",
  "signin.kicker": "沙盒模式",
  "signin.title": "你想如何使用 Lunas？",
  "signin.sub": "两种方式下所有流程都能用。用 PayPal 登录可获得属于自己的资料，或直接以共享访客演示进入。",
  "signin.home": "返回首页",
  "signin.pp.badge": "推荐",
  "signin.pp.kind": "PayPal 身份 API · 沙盒",
  "signin.pp.title": "使用 PayPal 登录",
  "signin.pp.body": "使用 PayPal 沙盒个人账户。我们只收到身份 API 分享的信息 —— 姓名、邮箱与 PayPal 账户 ID。密码绝不会传给我们。",
  "signin.pp.li1": "资料属于你：可编辑姓名、城市、简介与技能",
  "signin.pp.li2": "你的 PayPal 账户 ID 将成为收款账户",
  "signin.pp.li3": "退出登录会真正结束会话",
  "signin.pp.cta": "使用 PayPal 继续",
  "signin.pp.again": "切换 PayPal 账户",
  "signin.pp.off": "此部署未配置 PayPal 登录 —— 仍可使用访客模式。",
  "signin.guest.badge": "无需账户",
  "signin.guest.kind": "访客模式",
  "signin.guest.title": "以访客继续",
  "signin.guest.body": "直接使用 {name}（{city}）的共享演示资料，马上体验全部流程 —— 订单、托管、交付、放款。",
  "signin.guest.li1": "无需注册即可使用全部功能",
  "signin.guest.li2": "像真实用户一样编辑资料",
  "signin.guest.li3": "不会发送到任何地方，只保存在此浏览器",
  "signin.guest.cta": "以访客身份进入应用",
  "signin.note": "正在为黑客松测试本项目？PayPal 沙盒测试账户（邮箱 + 密码）写在仓库 README 中。支付仅在沙盒中进行，不涉及真实资金。",
  "signin.error.title": "登录未成功",
  "signin.error.paypal_not_configured": "此部署未配置 PayPal 登录。仍可使用访客模式。",
  "signin.error.cancelled": "你在 PayPal 页面取消了操作。",
  "signin.error.bad_state": "登录链接已过期，请重试。",
  "signin.error.no_code": "PayPal 未返回授权码。",
  "signin.error.generic": "PayPal 返回了错误。请重试，或以访客身份继续。",
  "me.id.fillCity": "添加你的城市",
  /* ---------- 头像、链接与作品集 ---------- */
  "nav.portfolio": "作品集",
  "me.f.photo": "头像",
  "me.photo.upload": "上传照片",
  "me.photo.busy": "处理中…",
  "me.photo.remove": "移除",
  "me.photo.hint": "正方形图片效果最好。会自动压缩到 512px 并保存在此浏览器中。",
  "me.photo.ready": "照片已就绪 — 记得点击保存。",
  "me.photo.err": "该文件无法作为图片读取。",
  "me.f.links": "链接",
  "me.f.x": "X（推特）",
  "me.f.linkedin": "领英",
  "me.f.instagram": "Instagram",
  "me.f.website": "网站",
  "me.f.portfolio": "作品集",
  "me.portfolio.add": "添加项目",
  "me.portfolio.title": "项目标题",
  "me.portfolio.url": "作品集链接",
  "me.portfolio.remove": "删除项目",
  "me.portfolio.hint": "最多 6 项 — 会显示在你的公开页面，让客户看到你的作品。",
  "me.links.title": "作品集与链接",
  "me.links.body": "客户在你的公开页面看到的就是这些。",
  "me.links.open": "打开",
  "me.links.empty": "还没有作品链接 — 添加几个，让客户看到你的作品。",
  "pub.portfolio": "作品集",

  /* ---------- 发布个人资料 ---------- */
  "me.saved.publishing": "保存中…",
  "me.saved.published": "已保存并发布 — 客户现在可以看到你的页面。",
  "me.saved.localOnly": "已保存在本设备。服务器存储尚未配置。",
  "me.saved.handleTaken": "该用户名已被占用 — 请换一个。",
  "me.saved.failed": "已保存在本地，但发布失败。请重试。",
  "me.publish.on": "已发布 — 客户可在 /to/{handle} 查看",
  "me.publish.off": "尚未发布 — 按“保存”即可发布",
  "me.publish.guest": "仅保存在本设备 — 使用 PayPal 登录后可发布",
  "me.saved.tableMissing": "已保存在本设备。缺少 Supabase 数据表 — 请先执行一次建表 SQL。",
  /* ---------- 隐藏账户信息 ---------- */
  "me.reveal": "显示详情",
  "me.hide": "隐藏详情",
  "me.mask.hint": "账户信息默认隐藏，避免出现在录屏中。",

  /* ---------- 洞察（AG Studio） ---------- */
  "nav.insights": "洞察",
  "ins.title": "你的收入，一目了然",
  "ins.sub": "每一笔托管订单、放款与智能体调用 — 变成一个你可以自由调整的仪表板。",
  "ins.kpi.escrow": "当前托管金额",
  "ins.kpi.released": "已放款给你",
  "ins.kpi.days": "平均放款天数",
  "ins.kpi.countries": "客户国家数",
  "ins.studio.t": "仪表板",
  "ins.studio.b": "从左侧拖动字段即可创建图表，点击图表可交叉筛选其余部件。布局保存在本浏览器中。",
  "ins.data.t": "数据来自哪里",
  "ins.data.b": "订单来自 Lunas；资金事件是背后的 PayPal 调用（Orders v2 收款、Payouts v1 放款、Payments v1 退款、手续费）；智能体调用包括合同、验证与调解。",
  "ins.engine": "AI 已验证",
  "ins.reset": "重置布局",
  "ins.loading": "正在加载仪表板…",
  "ins.licensed": "AG Studio Pro（黑客松试用，仅限评估）",

};

const id: Record<string, string> = {
  "ex.toClient": "Halo Aiko! Aku akan mendesain 6 slide Instagram untuk peluncuran studio keramikmu: 1080x1350 PNG, warna brand, dikirim sebelum Jumat. Harga $120.",
  "ex.fromClient": "Halo {name}! Aku butuh 20 foto produk diedit untuk toko online. Latar putih bersih, minimal 2000px, JPG. Bisa selesai sebelum Jumat? Budget $150.",
  "common.back": "Kembali",
  "common.next": "Lanjut",

  "nav.dashboard": "Beranda",
  "nav.orders": "Pesanan",
  "nav.newOrder": "Kirim pesanan",
  "nav.myPage": "Halaman pesananku",
  "nav.profile": "Profil",
  "theme.label": "Tema",
  "theme.candy": "Permen",
  "theme.midnight": "Tengah Malam",
  "theme.matcha": "Matcha",
  "me.menu.profile": "Lihat profil",
  "me.menu.public": "Halaman publikku",
  "me.menu.paypal": "PayPal & pencairan",
  "me.menu.signout": "Keluar",
  "me.toast.bye": "Keluar dari demo — sampai jumpa! 👋",
  "me.title": "Profilmu",
  "me.sub": "Identitas freelancer, preferensi, dan akun pembayaranmu.",
  "me.since": "Anggota sejak 2024",
  "me.langs": "Bahasa EN · ID · 中文",
  "me.edit": "Edit profil",
  "me.toast.edit": "Koneksi PayPal dikelola di dashboard sandbox PayPal 🙂",
  "me.save": "Simpan",
  "me.cancel": "Batal",
  "me.saved": "Profil tersimpan — sekarang ikut ke mana-mana.",
  "me.f.name": "Nama lengkap",
  "me.f.handle": "Handle (tautanmu: /to/…)",
  "me.f.city": "Kota",
  "me.f.country": "Kode negara",
  "me.f.bio": "Bio",
  "me.f.tags": "Keahlian (pisahkan dengan koma)",
  "me.stats.done": "Pesanan selesai",
  "me.stats.earned": "Total pendapatan",
  "me.stats.rating": "Rating klien",
  "me.prefs.theme": "Tema",
  "me.prefs.themeBody": "Pilih suasana — tersimpan otomatis.",
  "me.prefs.lang": "Bahasa",
  "me.prefs.langBody": "Bahasa untuk menu, tombol, dan email.",
  "me.paypal.title": "PayPal sandbox",
  "me.paypal.body": "Akun untuk escrow, pencairan, dan payout.",
  "me.paypal.connected": "Terhubung",
  "me.paypal.manage": "Kelola",
  "me.paypal.docs": "Dokumen API",
  "me.signoutCard": "Keluar dari demo ini",
  "me.signoutBody": "Bahasa dan temamu tetap tersimpan di perangkat ini.",
  "tip.title": "Tips dari Capi",
  "tip.body": "Ada {n} permintaan baru. Klien yang dibalas dalam 2 jam 3× lebih mungkin membayar!",
  "top.search": "Cari pesanan, klien…",
  "top.notifications": "Notifikasi",

  "status.request": "Permintaan baru",
  "status.awaiting_payment": "Menunggu pembayaran",
  "status.in_escrow": "Dana terkunci · dikerjakan",
  "status.verifying": "AI sedang mengecek",
  "status.revision": "Perlu diperbaiki",
  "status.review": "Klien sedang meninjau",
  "status.paid": "Lunas!",
  "status.declined": "Ditolak",

  "rail.paid": "{amount} sudah masuk ke PayPal {name} 🎉",
  "rail.held": "{amount} terkunci aman di escrow",
  "rail.declined": "Pesanan ditolak · tidak ada uang berpindah",
  "rail.notFunded": "Belum dibayar · tidak ada risiko",
  "rail.client": "Klien",
  "rail.escrow": "Escrow Lunas",
  "rail.you": "Kamu",
  "stamp.sub": "SUDAH DIBAYAR",

  "lp.nav.how": "Cara kerja",
  "lp.nav.who": "Untuk siapa",
  "lp.nav.try": "Coba stempelnya",
  "lp.openApp": "Buka aplikasi",
  "lp.kicker": "Escrow PayPal + AI untuk freelancer",
  "lp.h1.a": "Dibayar klien luar negeri,",
  "lp.h1.b": "tanpa was-was",
  "lp.h1.c": "dan langsung dicap.",
  "lp.sub": "Lunas mengubah brief yang berantakan jadi kontrak yang jelas, mengunci uangnya lewat PayPal, lalu AI mengecek hasil kerjamu. Kalau semua beres, tinggal cap LUNAS.",
  "lp.cta1": "Kirim pesanan pertamamu",
  "lp.cta2": "Lihat tampilan klien",
  "lp.trust1": "Aman dengan PayPal",
  "lp.trust2": "Hasil kerja dicek AI",
  "lp.trust3": "EN · 中文 · ID",
  "lp.scene.contract": "Perjanjian kerja",
  "lp.scene.job": "20 foto produk",
  "lp.scene.c1": "Tepat 20 file",
  "lp.scene.c2": "Format JPG",
  "lp.scene.c3": "Min. 2000px",
  "lp.scene.c4": "Latar putih",
  "lp.scene.passed": "lolos",

  "how.kicker": "4 langkah mungil",
  "how.title": "Cara kerja Lunas",
  "how.1.t": "Ceritakan",
  "how.1.b": "Tulis pekerjaannya seperti chat biasa. AI mengubahnya jadi syarat yang bisa dicek: jumlah file, ukuran, format, tenggat.",
  "how.2.t": "Kunci uangnya",
  "how.2.b": "Klien bayar lewat PayPal. Uang menunggu aman di escrow, nggak ada yang bisa kabur.",
  "how.3.t": "AI cek hasilnya",
  "how.3.b": "Upload hasil kerja. Agen AI mengecek setiap syarat dan minta revisi sebelum ada yang ribut.",
  "how.4.t": "Lunas!",
  "how.4.b": "Klien setuju (atau diam 72 jam), uang langsung masuk PayPal-mu. Cap!",

  "who.f.k": "Untuk freelancer",
  "who.f.t": "Nggak perlu nagih-nagih lagi",
  "who.f.1": "Tetap dibayar walau klien menghilang",
  "who.f.2": "Bye-bye revisi “dikit lagi ya…” tanpa akhir",
  "who.f.3": "Halaman pesanan sendiri, bisa dibagikan di mana saja",
  "who.f.4": "Bisa dengan klien dari negara mana pun",
  "who.c.k": "Untuk klien",
  "who.c.t": "Bayar di muka tanpa rasa takut",
  "who.c.1": "Uang baru cair kalau hasilnya sesuai",
  "who.c.2": "Syarat yang jelas, ditulis oleh AI",
  "who.c.3": "Bayar pakai akun PayPal atau kartu",
  "who.c.4": "Refund adil dan cepat kalau ada masalah",

  "try.kicker": "Ayo, pencet",
  "try.title": "Tombol paling memuaskan di dunia fintech",
  "try.body": "Di Indonesia, toko mencap nota “LUNAS” kalau sudah dibayar penuh. Tradisi itu kami bawa ke dunia digital.",
  "try.button": "Cap sekarang!",
  "try.again": "Cap lagi",
  "try.receipt": "Bukti pembayaran",
  "try.r.to": "Dibayar ke",
  "try.r.from": "Dibayar oleh",
  "try.r.check": "Verifikasi",
  "try.meaning": "“Lunas” artinya sudah dibayar penuh. Ya, sesimpel itu.",
  "cta.title": "Siap dibayar dengan benar?",
  "cta.body": "Gratis di sandbox. Cuma 2 menit. Capi sudah menunggu.",
  "foot.note": "Dibuat untuk PayPal AI Hackathon · berjalan di PayPal sandbox",
  "marq.1": "Jepang → Inggris",
  "marq.2": "Amerika Serikat → Indonesia",
  "marq.3": "Jerman → Indonesia",
  "marq.4": "Singapura → Indonesia",
  "marq.5": "Indonesia → Australia",
  "marq.6": "Spanyol → Indonesia",
  "marq.7": "Belanda → Indonesia",
  "marq.8": "Korea Selatan → Indonesia",
  "marq.9": "Indonesia → Jepang",
  "marq.10": "Kanada → Indonesia",
  "cert.title": "Sertifikat Penyelesaian",
  "cert.no": "No. Sertifikat",
  "cert.date": "Tanggal terbit",
  "cert.verified": "Diverifikasi AI Lunas · {n}/{n} kriteria terpenuhi",
  "cert.download": "Unduh sertifikat",
  "cert.hint": "PNG resolusi tinggi, siap dibingkai",
  "cert.toast": "Sertifikat tersimpan — bingkai ya! 🖼️",

  "dash.hi": "Selamat pagi, {name}!",
  "dash.summary": "Ada {r} permintaan baru dan {w} pesanan yang menunggumu. Yuk, mulai ngecap!",
  "dash.sendOrder": "Kirim pesanan ke klien",
  "dash.copyLink": "Salin link pesananku",
  "dash.capiSays": "Kamu keren banget!",
  "dash.stat.held": "Di escrow",
  "dash.stat.paid": "Sudah cair",
  "dash.stat.requests": "Permintaan baru",
  "dash.stat.release": "Rata-rata pencairan",
  "dash.stat.releaseVal": "1,8 hari",
  "dash.attention": "Perlu kamu tangani",
  "dash.seeAll": "Lihat semua",
  "dash.earnings": "Penghasilan mingguan",
  "dash.activity": "Aktivitas terbaru",
  "act.1": "Olivia menyetujui “Etsy banner” · $75 cair",
  "act.2": "Mei Lin mengirim permintaan baru",
  "act.3": "AI menemukan latar abu-abu di IMG_014",
  "act.4": "James menyetor $150 ke escrow",
  "time.min": "{n} menit lalu",
  "time.hour": "{n} jam lalu",
  "time.yesterday": "Kemarin",
  "order.due": "Tenggat {date}",
  "toast.copied": "Link disalin!",

  "orders.title": "Pesanan",
  "orders.sub": "Semua pesanan masuk dan keluar, di satu tempat yang ceria.",
  "orders.myPage": "Halaman pesananku",
  "orders.new": "Pesanan baru ke klien",
  "orders.tab.from": "Dari klien",
  "orders.tab.fromSub": "Klien memintamu mengerjakan sesuatu",
  "orders.tab.to": "Ke klien",
  "orders.tab.toSub": "Pesanan yang kamu kirim ke klien",
  "orders.newBadge": "{n} baru!",
  "filter.all": "Semua",
  "filter.action": "Perlu tindakan",
  "filter.escrow": "Berjalan",
  "filter.review": "Ditinjau",
  "filter.paid": "Lunas",
  "orders.empty": "Belum ada apa-apa di sini",
  "orders.emptySub": "Coba filter lain, atau kirim pesanan baru.",
  "orders.share.t": "Mau lebih banyak pesanan dari klien?",
  "orders.share.b": "Bagikan halaman pesananmu di Instagram, LinkedIn, atau WhatsApp. Klien cukup menulis kebutuhannya, AI yang membuat kontraknya.",
  "orders.share.preview": "Pratinjau",
  "cta.review": "Tinjau",
  "cta.remind": "Ingatkan",
  "cta.deliver": "Kirim hasil",
  "cta.view": "Lihat",
  "cta.fix": "Perbaiki",
  "cta.receipt": "Bukti",

  "new.title": "Kirim pesanan ke klien",
  "new.sub": "Tulis pekerjaannya sekali. Lunas membuatkan kontrak dan link pembayaran PayPal.",
  "new.s1": "Klien",
  "new.s2": "Pekerjaan",
  "new.s3": "Kontrak",
  "new.s4": "Kirim",
  "new.clientT": "Pesanan ini untuk siapa?",
  "new.clientB": "Kami akan mengirim email berisi link untuk meninjau dan membayar.",
  "new.clientName": "Nama klien",
  "new.clientEmail": "Email klien",
  "new.clientCountry": "Negara",
  "new.other": "Lainnya — ketik sendiri",
  "new.otherPh": "Nama negara, mis. Brasil",
  "new.currency": "Mata uang",
  "new.fillDemo": "Isi klien contoh",
  "new.jobT": "Apa yang akan kamu kirim?",
  "new.jobB": "Tulis seperti chat. Sertakan angka: berapa banyak, ukuran, format, kapan.",
  "new.briefLabel": "Deskripsi pekerjaan",
  "new.briefPh": "mis. 6 slide Instagram, 1080x1350 PNG, warna brand, sebelum Jumat, $120",
  "new.useExample": "Pakai contoh",
  "new.draftAI": "Buat kontrak dengan AI",
  "new.redraft": "Buat ulang",
  "new.aiHint": "AI mengubah kata-katamu jadi syarat yang bisa dicek.",
  "new.thinking": "Capi sedang membaca brief-mu…",
  "new.criteria": "Syarat penerimaan",
  "new.aiVerified": "Dicek AI",
  "new.agreement": "Perjanjian kerja",
  "new.orderTitle": "Judul pesanan",
  "new.draft": "Draf",
  "new.amount": "Harga",
  "new.due": "Tenggat",
  "new.window": "Waktu tinjau klien",
  "new.hours": "jam",
  "new.windowHint": "Kalau klien tidak merespons dalam {h} jam, uang otomatis cair ke kamu.",
  "new.addCrit": "Tambah syarat sendiri…",
  "new.clientPays": "Klien membayar",
  "new.fee": "Biaya Lunas (2,5%, dibayar klien)",
  "new.youGet": "Kamu terima",
  "new.send": "Buat & kirim",
  "new.sentT": "Pesanan terkirim!",
  "new.sentB": "Kami sudah mengirim email ke {name} berisi link untuk meninjau kontrak dan membayar lewat PayPal. Kamu akan dikabari begitu uangnya terkunci.",
  "new.copy": "Salin link",
  "new.email": "Kirim email lagi",
  "new.previewT": "Yang dilihat klienmu",
  "new.from": "Dari",
  "new.previewProtect": "Dilindungi escrow Lunas · tinjau {h} jam",
  "new.goOrder": "Lihat pesanan",
  "new.another": "Buat lagi",
  "pay.with": "Bayar dengan",

  "tl.agree": "Perjanjian",
  "tl.fund": "Dibayar",
  "tl.work": "Pengiriman",
  "tl.verify": "Cek AI",
  "tl.lunas": "Lunas",
  "toast.accepted": "Diterima! Link pembayaran terkirim.",
  "toast.funded": "Uang terkunci di escrow!",
  "decl.t": "Kamu menolak permintaan ini",
  "decl.b": "Klien sudah diberi tahu dengan sopan. Tidak ada uang berpindah.",
  "decl.undo": "Batalkan",
  "od.briefFrom": "brief asli",
  "od.window": "Waktu tinjau",
  "od.auto": "cair otomatis",
  "req.t": "{name} ingin bekerja sama denganmu!",
  "req.b": "AI sudah mengubah brief-nya jadi syarat yang jelas. Terima, atau usulkan perubahan.",
  "req.accept": "Terima · {amount}",
  "req.counter": "Usulkan perubahan",
  "req.decline": "Tolak",
  "pay.t": "Menunggu klien membayar",
  "pay.b": "Link pembayaran PayPal sudah dikirim ke {name}. Mulai kerja setelah uangnya terkunci.",
  "pay.remind": "Kirim pengingat",
  "demo.label": "Demo · simulasi klien",
  "pay.processing": "Memproses di PayPal sandbox…",
  "pay.captured": "Berhasil · terkunci",
  "pay.simulate": "Klien bayar dengan",
  "pay.sandbox": "PayPal sandbox · bayar dengan akun uji",
  "pay.loading": "Memuat PayPal sandbox…",
  "dl.t": "Waktunya kirim hasil!",
  "dl.b": "Uang sudah terkunci. Upload file-mu dan biarkan AI mengeceknya sesuai kontrak.",
  "dl.verT": "AI sedang mengecek file-mu…",
  "dl.verB": "Satu per satu, sesuai kontrak. Bukan soal selera.",
  "dl.revT": "Dikit lagi! Ada satu yang perlu diperbaiki",
  "dl.revB": "Uang tetap terkunci aman selama kamu memperbaikinya.",
  "dl.drop": "Taruh file-mu di sini",
  "dl.dropSub": "atau klik untuk upload · demo memakai gambar contoh",
  "dl.run": "Jalankan cek AI",
  "dl.agentSays": "Agen verifikasi",
  "dl.agentMsg": "IMG_014 latarnya abu-abu muda (21% piksel tidak putih). Perbaiki lalu upload ulang. Sisanya sudah sempurna!",
  "dl.reupload": "Upload ulang file yang sudah diperbaiki",
  "rev.t": "Semua lolos! Klien sedang meninjau",
  "rev.b": "{name} bisa menyetujui sekarang. Kalau diam saja, kamu tetap dibayar otomatis.",
  "rev.until": "sampai cair otomatis",
  "rev.safe": "Uangmu terlindungi",
  "rev.explain": "Klien hanya bisa komplain dengan alasan yang terkait syarat di kontrak. Diam berarti setuju.",
  "rev.simulate": "Klien menyetujui",
  "rev.releasing": "Mencairkan…",
  "paid.t": "LUNAS! Kamu sudah dibayar",
  "paid.b": "{amount} dikirim ke PayPal-mu lewat Payouts.",
  "log.title": "Aktivitas agen",
  "med.t": "Meja sengketa · Mediator Agent",
  "med.b": "Kurang puas dengan hasilnya? Tulis alasannya. Mediator membaca bukti kontrak lalu memutuskan dana escrow.",
  "med.chips": "Contoh komplain",
  "med.chip.1": "3 slide tidak sesuai warna brief, dan pengirimannya terlambat.",
  "med.chip.2": "Saya belum terima file-nya sama sekali, dan sudah lewat deadline seminggu.",
  "med.chip.3": "Dari 20 foto cuma 14 yang masuk, IMG_007 buram tidak bisa dipakai.",
  "med.chip.4": "Keren banget, mantap — cuma satu typo kecil di slide 2.",
  "med.ph": "mis. Dari 20 foto cuma 14 yang masuk, dan IMG_007 latarnya masih abu-abu…",
  "med.ask": "Minta putusan Mediator",
  "med.thinking": "Sedang membaca bukti…",
  "med.short": "Tulis dulu beberapa kata — Mediator butuh komplain untuk diputuskan.",
  "med.verdict": "Putusan Mediator",
  "med.dec.release": "Cairkan ke freelancer",
  "med.dec.refund_partial": "Refund sebagian",
  "med.dec.refund_full": "Refund penuh",
  "med.dec.escalate": "Eskalasi ke manusia",
  "med.amount": "{p}% dari {amt} kembali ke klien",
  "med.conf": "Keyakinan",
  "med.why": "Alasan",
  "med.signals": "Sinyal yang dipakai",
  "med.next": "Langkah berikutnya",
  "med.src.llm": "putusan LLM",
  "med.src.local": "mesin aturan lokal",
  "med.capture": "PayPal capture ID",
  "med.exec": "Jalankan refund di PayPal",
  "med.executing": "Memanggil Refunds API…",
  "med.simulate": "Jalankan refund (demo)",
  "med.nocap": "Belum ada capture sandbox tercatat — jalan sebagai demo",
  "med.done": "Refund {status} · {id}",
  "med.err": "Refund gagal",
  "med.voided": "Sertifikat dibatalkan — {p}% dikembalikan ke klien",
  "med.frozen": "Dana tetap dibeku sampai mediator manusia memutuskan",

  "pub.imSari": "Aku {name} →",
  "pub.bio": "Editor foto produk & desainer dari Yogyakarta. Bikin toko online kelihatan menggoda. 6 tahun, 86 klien puas, nol drama.",
  "pub.skill1": "Edit foto",
  "pub.skill2": "Desain media sosial",
  "pub.skill3": "Logo",
  "pub.skill4": "Etsy & Shopify",
  "pub.rating": "rating",
  "pub.done": "pesanan selesai",
  "pub.release": "rata-rata kirim",
  "pub.protectT": "Kamu dilindungi Lunas",
  "pub.protectB": "Pembayaranmu ditahan di escrow dan baru cair kalau hasilnya sesuai kontrak.",
  "pub.kicker": "Permintaan pesanan",
  "pub.title": "Pesan jasa {name} dalam 2 menit",
  "pub.sub": "Ceritakan kebutuhanmu. AI mengubahnya jadi kontrak jelas yang dipercaya kedua pihak.",
  "pub.yourName": "Nama kamu",
  "pub.yourEmail": "Email kamu",
  "pub.briefPh": "mis. Saya butuh 20 foto produk diedit, latar putih, JPG, sebelum Jumat. Budget $150.",
  "pub.budget": "Budget (USD)",
  "pub.send": "Kirim permintaan",
  "pub.noPayYet": "Belum perlu bayar apa pun. Kamu baru bayar lewat PayPal setelah {name} menerima.",
  "pub.sentT": "Permintaan terkirim!",
  "pub.sentB": "{name} biasanya membalas dalam beberapa jam. Kami akan mengirim email ke {email} begitu dia menerima.",
  "pub.next1": "{name} meninjau permintaan & kontrakmu",
  "pub.next2": "Kamu bayar {amount} lewat PayPal ke escrow",
  "pub.next3": "AI mengecek hasilnya, lalu kamu setujui. Lunas!",
  "pub.seeAsSari": "Lihat sebagai {name}",
  "pub.another": "Kirim lagi",
  /* ---------- masuk & identitas (PayPal sandbox + tamu) ---------- */
  "lp.signin": "Masuk",
  "me.menu.signin": "Masuk dengan PayPal",
  "me.menu.connected": "Akun PayPal tersambung",
  "me.signed.pp": "Masuk dengan PayPal (sandbox)",
  "me.toast.welcome": "Masuk sebagai {name} — lengkapi profilmu!",
  "me.id.pp": "Kamu masuk dengan PayPal (sandbox)",
  "me.id.ppBody": "Tersambung sebagai {email}. Profil ini milik akun PayPal tersebut — semua kolom di bawah bisa kamu ubah.",
  "me.id.account": "ID akun PayPal:",
  "me.id.guest": "Kamu sedang memakai mode tamu",
  "me.id.guestBody": "Ini profil demo bersama ({name}, {city}). Masuk dengan PayPal supaya profil ini menjadi milikmu.",
  "me.paypal.notConnected": "Belum tersambung",
  "me.paypal.bodyLive": "Pencairan dari profil ini masuk ke akun PayPal yang kamu pakai untuk masuk.",
  "me.paypal.bodyGuest": "Masuk dengan akun PayPal sandbox untuk menyambungkan pencairan ke akunmu sendiri.",
  "signin.kicker": "Mode sandbox",
  "signin.title": "Mau memakai Lunas sebagai apa?",
  "signin.sub": "Semua alur tetap berfungsi di kedua cara. Masuk dengan PayPal untuk punya profil sendiri, atau langsung coba sebagai tamu.",
  "signin.home": "Kembali ke situs",
  "signin.pp.badge": "Disarankan",
  "signin.pp.kind": "PayPal Identity API · sandbox",
  "signin.pp.title": "Masuk dengan PayPal",
  "signin.pp.body": "Pakai akun personal PayPal sandbox. Kami hanya menerima data dari Identity API — nama, email, dan ID akun PayPal. Password tidak pernah sampai ke kami.",
  "signin.pp.li1": "Profilnya milikmu: ubah nama, kota, bio, dan keahlian",
  "signin.pp.li2": "ID akun PayPal-mu jadi penerima pencairan dana",
  "signin.pp.li3": "Tombol keluar benar-benar mengakhiri sesi",
  "signin.pp.cta": "Lanjutkan dengan PayPal",
  "signin.pp.again": "Ganti akun PayPal",
  "signin.pp.off": "Login PayPal belum dikonfigurasi di deployment ini — mode tamu tetap bisa.",
  "signin.guest.badge": "Tanpa akun",
  "signin.guest.kind": "Mode tamu",
  "signin.guest.title": "Lanjut sebagai tamu",
  "signin.guest.body": "Pakai profil demo bersama {name} di {city} dan coba semua alur sekarang — order, escrow, pengiriman, pencairan.",
  "signin.guest.li1": "Semua fitur terbuka, tanpa daftar",
  "signin.guest.li2": "Profil bisa diubah seperti pengguna biasa",
  "signin.guest.li3": "Tidak dikirim ke mana pun, hanya di browser ini",
  "signin.guest.cta": "Masuk sebagai tamu",
  "signin.note": "Sedang menguji proyek ini untuk hackathon? Akun tester PayPal sandbox (email + password) tercantum di README repositori. Pembayaran hanya di sandbox — tidak ada uang nyata yang berpindah.",
  "signin.error.title": "Tidak berhasil masuk",
  "signin.error.paypal_not_configured": "Login PayPal belum dikonfigurasi di deployment ini. Mode tamu tetap bisa.",
  "signin.error.cancelled": "Kamu membatalkan di halaman PayPal.",
  "signin.error.bad_state": "Tautan masuk sudah kedaluwarsa. Coba lagi.",
  "signin.error.no_code": "PayPal tidak mengirim kode otorisasi.",
  "signin.error.generic": "PayPal mengembalikan error. Coba lagi, atau lanjut sebagai tamu.",
  "me.id.fillCity": "tambahkan kotamu",
  /* ---------- foto profil, tautan & portofolio ---------- */
  "nav.portfolio": "Portofolio",
  "me.f.photo": "Foto profil",
  "me.photo.upload": "Unggah foto",
  "me.photo.busy": "Memproses…",
  "me.photo.remove": "Hapus",
  "me.photo.hint": "Foto persegi paling pas. Otomatis diperkecil ke 512px dan disimpan di browser ini.",
  "me.photo.ready": "Foto siap — jangan lupa tekan Simpan.",
  "me.photo.err": "Berkas itu tidak bisa dibaca sebagai gambar.",
  "me.f.links": "Tautan",
  "me.f.x": "X (Twitter)",
  "me.f.linkedin": "LinkedIn",
  "me.f.instagram": "Instagram",
  "me.f.website": "Situs web",
  "me.f.portfolio": "Portofolio",
  "me.portfolio.add": "Tambah item",
  "me.portfolio.title": "Judul proyek",
  "me.portfolio.url": "Tautan portofolio",
  "me.portfolio.remove": "Hapus item",
  "me.portfolio.hint": "Maksimal 6 item — muncul di halaman publikmu supaya klien bisa melihat hasil kerjamu.",
  "me.links.title": "Portofolio & tautan",
  "me.links.body": "Inilah yang dilihat klien di halaman publikmu.",
  "me.links.open": "Buka",
  "me.links.empty": "Belum ada tautan portofolio — tambahkan supaya klien bisa melihat hasil kerjamu.",
  "pub.portfolio": "Portofolio",

  /* ---------- menerbitkan profil ---------- */
  "me.saved.publishing": "Menyimpan…",
  "me.saved.published": "Tersimpan & terbit — klien sudah bisa melihat halamanmu.",
  "me.saved.localOnly": "Tersimpan di perangkat ini. Penyimpanan server belum dikonfigurasi.",
  "me.saved.handleTaken": "Username itu sudah dipakai — pilih yang lain.",
  "me.saved.failed": "Tersimpan di sini, tapi gagal diterbitkan. Coba lagi.",
  "me.publish.on": "Terbit — klien melihatnya di /to/{handle}",
  "me.publish.off": "Belum terbit — tekan Simpan untuk menerbitkan",
  "me.publish.guest": "Hanya di perangkat ini — masuk dengan PayPal untuk menerbitkan",
  "me.saved.tableMissing": "Tersimpan di perangkat ini. Tabel Supabase belum ada — jalankan SQL setup sekali saja.",
  /* ---------- sembunyikan detail akun ---------- */
  "me.reveal": "Tampilkan detail",
  "me.hide": "Sembunyikan detail",
  "me.mask.hint": "Detail akun disembunyikan supaya tidak ikut terekam saat membuat video.",

  /* ---------- insights (AG Studio) ---------- */
  "nav.insights": "Insights",
  "ins.title": "Uangmu, dalam satu tampilan",
  "ins.sub": "Setiap order escrow, pencairan, dan pemanggilan agen — jadi dashboard yang bisa kamu atur sendiri.",
  "ins.kpi.escrow": "Sedang di escrow",
  "ins.kpi.released": "Sudah cair ke kamu",
  "ins.kpi.days": "Rata-rata hari cair",
  "ins.kpi.countries": "Negara klien",
  "ins.studio.t": "Dashboard",
  "ins.studio.b": "Tarik sebuah kolom dari panel kiri untuk membuat grafik, atau klik satu grafik untuk memfilter widget lainnya. Tata letaknya tersimpan di browser ini.",
  "ins.data.t": "Dari mana datanya",
  "ins.data.b": "Order diambil dari Lunas; money events adalah panggilan PayPal di baliknya (Orders v2 untuk masuk escrow, Payouts v1 untuk pencairan, Payments v1 untuk refund, plus biaya); agent runs adalah pemanggilan agen kontrak, verifikasi, dan mediasi.",
  "ins.engine": "Terverifikasi AI",
  "ins.reset": "Atur ulang tata letak",
  "ins.loading": "Memuat dashboard…",
  "ins.licensed": "AG Studio Pro (trial hackathon, hanya untuk evaluasi)",

};

export const dict: Record<Lang, Record<string, string>> = { en, zh, id };
