export type Lang = "en" | "zh" | "id";

/* English is the source of truth. Missing keys in zh/id fall back to English. */
const en: Record<string, string> = {
  "ex.toClient": "Hi Aiko! I'll design 6 Instagram slides for your ceramics studio launch: 1080x1350 PNG, brand colors, delivered by Friday. Price $120.",
  "ex.fromClient": "Hi Sari! I need 20 product photos edited for my online store. Clean white background, at least 2000px, JPG. Can you deliver by Friday? Budget is $150.",
  "common.back": "Back",
  "common.next": "Next",

  "nav.dashboard": "Dashboard",
  "nav.orders": "Orders",
  "nav.newOrder": "Send an order",
  "nav.myPage": "My order page",
  "nav.profile": "Profile",
  "theme.label": "Theme",
  "theme.candy": "Candy",
  "theme.midnight": "Midnight",
  "theme.matcha": "Matcha",
  "me.menu.profile": "View profile",
  "me.menu.public": "My public page",
  "me.menu.paypal": "PayPal & payouts",
  "me.menu.signout": "Sign out",
  "me.toast.bye": "Signed out of the demo — see you soon! 👋",
  "me.title": "Your profile",
  "me.sub": "Your freelancer identity, preferences and payout account.",
  "me.since": "Member since 2024",
  "me.langs": "Speaks EN · ID · 中文",
  "me.edit": "Edit profile",
  "me.toast.edit": "Profile editing arrives with the real backend 🙂",
  "me.stats.done": "Orders completed",
  "me.stats.earned": "Total earned",
  "me.stats.rating": "Client rating",
  "me.prefs.theme": "Theme",
  "me.prefs.themeBody": "Pick a vibe — it saves automatically.",
  "me.prefs.lang": "Language",
  "me.prefs.langBody": "Language for menus, buttons and emails.",
  "me.paypal.title": "PayPal sandbox",
  "me.paypal.body": "Account used for escrow, releases and payouts.",
  "me.paypal.connected": "Connected",
  "me.paypal.manage": "Manage",
  "me.paypal.docs": "API docs",
  "me.signoutCard": "Sign out of this demo",
  "me.signoutBody": "Your language and theme stay saved on this device.",
  "tip.title": "Capi's tip",
  "tip.body": "You have {n} new requests. Clients who get a reply within 2 hours are 3× more likely to pay!",
  "top.search": "Search orders, clients…",
  "top.notifications": "Notifications",

  "status.request": "New request",
  "status.awaiting_payment": "Waiting for payment",
  "status.in_escrow": "Funds locked · working",
  "status.verifying": "AI is checking",
  "status.revision": "Needs a fix",
  "status.review": "Client reviewing",
  "status.paid": "Lunas! Paid",
  "status.declined": "Declined",

  "rail.paid": "{amount} landed in {name}'s PayPal 🎉",
  "rail.held": "{amount} is safely locked in escrow",
  "rail.declined": "Order declined · no money moved",
  "rail.notFunded": "Not funded yet · nothing at risk",
  "rail.client": "Client",
  "rail.escrow": "Lunas escrow",
  "rail.you": "You",
  "stamp.sub": "PAID IN FULL",

  "lp.nav.how": "How it works",
  "lp.nav.who": "Who it's for",
  "lp.nav.try": "Try the stamp",
  "lp.openApp": "Open app",
  "lp.kicker": "PayPal + AI escrow for freelancers",
  "lp.h1.a": "Get paid by clients abroad,",
  "lp.h1.b": "worry-free",
  "lp.h1.c": "and stamped.",
  "lp.sub": "Lunas turns a messy brief into a clear contract, locks the money with PayPal, and lets AI check the work. When everything's done, it's LUNAS — paid in full.",
  "lp.cta1": "Send your first order",
  "lp.cta2": "See a client's view",
  "lp.trust1": "PayPal-secured",
  "lp.trust2": "AI-verified work",
  "lp.trust3": "EN · 中文 · ID",
  "lp.scene.contract": "Work agreement",
  "lp.scene.job": "20 product photos",
  "lp.scene.c1": "Exactly 20 files",
  "lp.scene.c2": "JPG format",
  "lp.scene.c3": "Min. 2000px",
  "lp.scene.c4": "White background",
  "lp.scene.passed": "passed",

  "how.kicker": "4 tiny steps",
  "how.title": "How Lunas works",
  "how.1.t": "Describe it",
  "how.1.b": "Type the job like a chat message. AI turns it into checkable terms: file count, size, format, deadline.",
  "how.2.t": "Lock the money",
  "how.2.b": "The client pays with PayPal. Money waits safely in escrow. Nobody can run away with it.",
  "how.3.t": "AI checks the work",
  "how.3.b": "Upload the delivery. Our agent checks every criterion and asks for fixes before anyone argues.",
  "how.4.t": "Lunas!",
  "how.4.b": "Client approves (or stays silent for 72h) and the money lands in your PayPal. Stamp!",

  "who.f.k": "For freelancers",
  "who.f.t": "Never chase an invoice again",
  "who.f.1": "Get paid even if the client goes quiet",
  "who.f.2": "No more endless “one small change…”",
  "who.f.3": "Your own order page to share anywhere",
  "who.f.4": "Works with clients from any country",
  "who.c.k": "For clients",
  "who.c.t": "Pay upfront without the fear",
  "who.c.1": "Money is only released when the work matches",
  "who.c.2": "Clear terms written for you by AI",
  "who.c.3": "Pay with your PayPal account or card",
  "who.c.4": "Fair, fast refunds if something goes wrong",

  "try.kicker": "Go on, press it",
  "try.title": "The most satisfying button in fintech",
  "try.body": "In Indonesia, shops stamp a receipt “LUNAS” when it's paid in full. We kept the tradition, digitally.",
  "try.button": "Stamp it!",
  "try.again": "Stamp again",
  "try.receipt": "Payment receipt",
  "try.r.to": "Paid to",
  "try.r.from": "Paid by",
  "try.r.check": "Verification",
  "try.meaning": "“Lunas” (loo-nahs) is Indonesian for paid in full.",
  "cta.title": "Ready to get paid properly?",
  "cta.body": "Free in sandbox. Takes 2 minutes. Capi is waiting.",
  "foot.note": "Built for the PayPal AI Hackathon · runs on the PayPal sandbox",

  "dash.hi": "Good morning, {name}!",
  "dash.summary": "You have {r} new requests and {w} orders waiting for you. Let's get stamping!",
  "dash.sendOrder": "Send order to a client",
  "dash.copyLink": "Copy my order link",
  "dash.capiSays": "You're doing great!",
  "dash.stat.held": "In escrow",
  "dash.stat.paid": "Paid out",
  "dash.stat.requests": "New requests",
  "dash.stat.release": "Avg. payout time",
  "dash.stat.releaseVal": "1.8 days",
  "dash.attention": "Needs your attention",
  "dash.seeAll": "See all",
  "dash.earnings": "Weekly earnings",
  "dash.activity": "Recent activity",
  "act.1": "Olivia approved “Etsy banner” · $75 paid",
  "act.2": "Mei Lin sent you a new request",
  "act.3": "AI found a grey background in IMG_014",
  "act.4": "James funded $150 into escrow",
  "time.min": "{n} min ago",
  "time.hour": "{n} h ago",
  "time.yesterday": "Yesterday",
  "order.due": "Due {date}",
  "toast.copied": "Link copied!",

  "orders.title": "Orders",
  "orders.sub": "Everything coming in and going out, in one happy place.",
  "orders.myPage": "My order page",
  "orders.new": "New order to client",
  "orders.tab.from": "From clients",
  "orders.tab.fromSub": "Clients asked you to do work",
  "orders.tab.to": "To clients",
  "orders.tab.toSub": "Orders you sent to clients",
  "orders.newBadge": "{n} new!",
  "filter.all": "All",
  "filter.action": "Needs action",
  "filter.escrow": "Active",
  "filter.review": "In review",
  "filter.paid": "Lunas",
  "orders.empty": "Nothing here yet",
  "orders.emptySub": "Try another filter, or send a new order.",
  "orders.share.t": "Want more orders from clients?",
  "orders.share.b": "Share your order page on Instagram, LinkedIn or WhatsApp. Clients describe the job, AI writes the contract.",
  "orders.share.preview": "Preview",
  "cta.review": "Review",
  "cta.remind": "Remind",
  "cta.deliver": "Deliver",
  "cta.view": "View",
  "cta.fix": "Fix it",
  "cta.receipt": "Receipt",

  "new.title": "Send an order to a client",
  "new.sub": "Write the job once. Lunas makes the contract and a PayPal payment link.",
  "new.s1": "Client",
  "new.s2": "The job",
  "new.s3": "Contract",
  "new.s4": "Send",
  "new.clientT": "Who is this for?",
  "new.clientB": "We'll email them a link to review and pay.",
  "new.clientName": "Client name",
  "new.clientEmail": "Client email",
  "new.clientCountry": "Country",
  "new.currency": "Currency",
  "new.fillDemo": "Fill demo client",
  "new.jobT": "What will you deliver?",
  "new.jobB": "Write it like a message. Include numbers: how many, what size, what format, when.",
  "new.briefLabel": "Job description",
  "new.briefPh": "e.g. 6 Instagram slides, 1080x1350 PNG, brand colors, by Friday, $120",
  "new.useExample": "Use an example",
  "new.draftAI": "Draft contract with AI",
  "new.redraft": "Draft again",
  "new.aiHint": "AI turns your words into checkable criteria.",
  "new.thinking": "Capi is reading your brief…",
  "new.criteria": "Acceptance criteria",
  "new.aiVerified": "AI-verified",
  "new.agreement": "Work agreement",
  "new.orderTitle": "Order title",
  "new.draft": "Draft",
  "new.amount": "Price",
  "new.due": "Deadline",
  "new.window": "Client review window",
  "new.hours": "hours",
  "new.windowHint": "If the client doesn't respond within {h} hours, the money is released to you automatically.",
  "new.addCrit": "Add your own criterion…",
  "new.clientPays": "Client pays",
  "new.fee": "Lunas fee (2.5%, paid by client)",
  "new.youGet": "You receive",
  "new.send": "Create & send",
  "new.sentT": "Order sent!",
  "new.sentB": "We emailed {name} a link to review the contract and pay with PayPal. We'll ping you the moment the money is locked.",
  "new.copy": "Copy link",
  "new.email": "Email again",
  "new.previewT": "What your client sees",
  "new.from": "From",
  "new.previewProtect": "Protected by Lunas escrow · {h}h review",
  "new.goOrder": "Go to order",
  "new.another": "Create another",
  "pay.with": "Pay with",

  "tl.agree": "Agreement",
  "tl.fund": "Funded",
  "tl.work": "Delivery",
  "tl.verify": "AI check",
  "tl.lunas": "Lunas",
  "toast.accepted": "Accepted! Payment link sent.",
  "toast.funded": "Money locked in escrow!",
  "decl.t": "You declined this request",
  "decl.b": "The client was notified kindly. No money moved.",
  "decl.undo": "Undo",
  "od.briefFrom": "original brief",
  "od.window": "Review window",
  "od.auto": "auto-release",
  "req.t": "{name} wants to work with you!",
  "req.b": "AI already turned their brief into clear criteria. Accept, or suggest changes.",
  "req.accept": "Accept · {amount}",
  "req.counter": "Suggest changes",
  "req.decline": "Decline",
  "pay.t": "Waiting for the client to pay",
  "pay.b": "We sent {name} a PayPal payment link. Start working once the money is locked.",
  "pay.remind": "Send reminder",
  "demo.label": "Demo · simulate the client",
  "pay.processing": "Capturing in PayPal sandbox…",
  "pay.captured": "Captured · locked",
  "pay.simulate": "Client pays with",
  "dl.t": "Time to deliver!",
  "dl.b": "Money is locked. Upload your files and let AI check them against the contract.",
  "dl.verT": "AI is checking your files…",
  "dl.verB": "Every criterion, one by one. No opinions, just the contract.",
  "dl.revT": "Almost there! One thing to fix",
  "dl.revB": "The money stays safely locked while you fix it.",
  "dl.drop": "Drop your files here",
  "dl.dropSub": "or click to upload · demo uses sample images",
  "dl.run": "Run AI check",
  "dl.agentSays": "Verification agent",
  "dl.agentMsg": "IMG_014 has a light-grey background (21% non-white pixels). Fix it and re-upload. Everything else is perfect!",
  "dl.reupload": "Re-upload fixed file",
  "rev.t": "All checks passed! Client is reviewing",
  "rev.b": "{name} can approve now. If they stay silent, you get paid automatically.",
  "rev.until": "until auto-release",
  "rev.safe": "Your money is protected",
  "rev.explain": "The client can only dispute with a reason linked to a criterion. Silence means approval.",
  "rev.simulate": "Client approves",
  "rev.releasing": "Releasing…",
  "paid.t": "LUNAS! You got paid",
  "paid.b": "{amount} was sent to your PayPal via Payouts.",
  "log.title": "Agent activity",

  "pub.imSari": "I'm Sari →",
  "pub.bio": "Product photo editor & designer from Yogyakarta. I make online shops look delicious. 6 years, 86 happy clients, zero drama.",
  "pub.skill1": "Photo editing",
  "pub.skill2": "Social media design",
  "pub.skill3": "Logos",
  "pub.skill4": "Etsy & Shopify",
  "pub.rating": "rating",
  "pub.done": "orders done",
  "pub.release": "avg. delivery",
  "pub.protectT": "You're protected by Lunas",
  "pub.protectB": "Your payment is held in escrow and only released when the work matches the contract.",
  "pub.kicker": "Order request",
  "pub.title": "Hire {name} in 2 minutes",
  "pub.sub": "Describe what you need. AI turns it into a clear contract you can both trust.",
  "pub.yourName": "Your name",
  "pub.yourEmail": "Your email",
  "pub.briefPh": "e.g. I need 20 product photos edited, white background, JPG, by Friday. Budget $150.",
  "pub.budget": "Budget (USD)",
  "pub.send": "Send request",
  "pub.noPayYet": "You won't pay anything yet. You'll pay with PayPal only after Sari accepts.",
  "pub.sentT": "Request sent!",
  "pub.sentB": "{name} usually replies within a few hours. We'll email {email} when she accepts.",
  "pub.next1": "Sari reviews your request & contract",
  "pub.next2": "You pay {amount} with PayPal into escrow",
  "pub.next3": "AI checks the work, then you approve. Lunas!",
  "pub.seeAsSari": "See it as Sari",
  "pub.another": "Send another",
};

const zh: Record<string, string> = {
  "ex.toClient": "你好 Aiko！我会为你的陶瓷工作室新品发布设计 6 张 Instagram 图：1080x1350 PNG，品牌色，周五前交付。价格 $120。",
  "ex.fromClient": "你好 Sari！我需要修 20 张产品照片，用于我的网店。纯白背景，至少 2000px，JPG 格式。周五前能交吗？预算 $150。",
  "common.back": "返回",
  "common.next": "下一步",

  "nav.dashboard": "概览",
  "nav.orders": "订单",
  "nav.newOrder": "发送订单",
  "nav.myPage": "我的接单页",
  "nav.profile": "个人资料",
  "theme.label": "主题",
  "theme.candy": "糖果",
  "theme.midnight": "午夜",
  "theme.matcha": "抹茶",
  "me.menu.profile": "查看资料",
  "me.menu.public": "我的公开页",
  "me.menu.paypal": "PayPal 与收款",
  "me.menu.signout": "退出登录",
  "me.toast.bye": "已退出演示 — 再见！👋",
  "me.title": "你的资料",
  "me.sub": "你的自由职业身份、偏好与收款账户。",
  "me.since": "2024 年加入",
  "me.langs": "语言 EN · ID · 中文",
  "me.edit": "编辑资料",
  "me.toast.edit": "资料编辑将随真实后端上线 🙂",
  "me.stats.done": "已完成订单",
  "me.stats.earned": "累计收入",
  "me.stats.rating": "客户评分",
  "me.prefs.theme": "主题",
  "me.prefs.themeBody": "选一个风格，自动保存。",
  "me.prefs.lang": "语言",
  "me.prefs.langBody": "菜单、按钮与邮件使用的语言。",
  "me.paypal.title": "PayPal 沙盒",
  "me.paypal.body": "用于托管、放款与收款的账户。",
  "me.paypal.connected": "已连接",
  "me.paypal.manage": "管理",
  "me.paypal.docs": "API 文档",
  "me.signoutCard": "退出此演示",
  "me.signoutBody": "语言与主题仍会保存在此设备上。",
  "tip.title": "Capi 小贴士",
  "tip.body": "你有 {n} 个新请求。2 小时内回复的客户，付款概率高 3 倍哦！",
  "top.search": "搜索订单、客户…",
  "top.notifications": "通知",

  "status.request": "新请求",
  "status.awaiting_payment": "等待付款",
  "status.in_escrow": "资金已锁定 · 进行中",
  "status.verifying": "AI 检查中",
  "status.revision": "需要修改",
  "status.review": "客户审核中",
  "status.paid": "Lunas！已付清",
  "status.declined": "已拒绝",

  "rail.paid": "{amount} 已到账 {name} 的 PayPal 🎉",
  "rail.held": "{amount} 已安全锁定在托管中",
  "rail.declined": "订单已拒绝 · 资金未变动",
  "rail.notFunded": "尚未付款 · 没有任何风险",
  "rail.client": "客户",
  "rail.escrow": "Lunas 托管",
  "rail.you": "你",
  "stamp.sub": "已全额付清",

  "lp.nav.how": "如何运作",
  "lp.nav.who": "适合谁",
  "lp.nav.try": "试试盖章",
  "lp.openApp": "打开应用",
  "lp.kicker": "为自由职业者打造的 PayPal + AI 托管",
  "lp.h1.a": "收海外客户的钱，",
  "lp.h1.b": "安心无忧",
  "lp.h1.c": "一章搞定。",
  "lp.sub": "Lunas 把模糊的需求变成清晰的合同，用 PayPal 锁定资金，再让 AI 检查交付成果。一切完成后，盖上 LUNAS —— 全额付清。",
  "lp.cta1": "发送第一笔订单",
  "lp.cta2": "查看客户视角",
  "lp.trust1": "PayPal 安全保障",
  "lp.trust2": "AI 验收作品",
  "lp.trust3": "EN · 中文 · ID",
  "lp.scene.contract": "工作协议",
  "lp.scene.job": "20 张产品照片",
  "lp.scene.c1": "正好 20 个文件",
  "lp.scene.c2": "JPG 格式",
  "lp.scene.c3": "至少 2000px",
  "lp.scene.c4": "纯白背景",
  "lp.scene.passed": "通过",

  "how.kicker": "简单 4 步",
  "how.title": "Lunas 如何运作",
  "how.1.t": "描述需求",
  "how.1.b": "像发消息一样描述工作。AI 会把它变成可检查的条款：文件数量、尺寸、格式、截止日期。",
  "how.2.t": "锁定资金",
  "how.2.b": "客户用 PayPal 付款，资金安全地保存在托管中，谁也拿不走。",
  "how.3.t": "AI 检查作品",
  "how.3.b": "上传交付文件，AI 代理逐条检查标准，在争执发生前就提出修改。",
  "how.4.t": "Lunas！",
  "how.4.b": "客户确认（或 72 小时内未回应），钱就会到你的 PayPal。盖章！",

  "who.f.k": "给自由职业者",
  "who.f.t": "再也不用追着要钱",
  "who.f.1": "客户失联也能收到钱",
  "who.f.2": "告别没完没了的“再改一点点…”",
  "who.f.3": "专属接单页，随处分享",
  "who.f.4": "支持任何国家的客户",
  "who.c.k": "给客户",
  "who.c.t": "放心预付，不再担心",
  "who.c.1": "作品符合要求才会放款",
  "who.c.2": "AI 帮你写好清晰的条款",
  "who.c.3": "用 PayPal 账户或银行卡支付",
  "who.c.4": "出问题时公平、快速退款",

  "try.kicker": "来，按一下",
  "try.title": "金融科技里最解压的按钮",
  "try.body": "在印尼，商店会在付清的收据上盖“LUNAS”章。我们把这个传统搬到了线上。",
  "try.button": "盖章！",
  "try.again": "再盖一次",
  "try.receipt": "付款收据",
  "try.r.to": "收款人",
  "try.r.from": "付款人",
  "try.r.check": "验收",
  "try.meaning": "“Lunas”（鲁-纳斯）在印尼语里意思是“全额付清”。",
  "cta.title": "准备好安心收款了吗？",
  "cta.body": "沙盒环境免费使用，2 分钟上手。Capi 在等你。",
  "foot.note": "为 PayPal AI 黑客松打造 · 运行于 PayPal 沙盒",

  "dash.hi": "早上好，{name}！",
  "dash.summary": "你有 {r} 个新请求和 {w} 个待处理订单。一起去盖章吧！",
  "dash.sendOrder": "给客户发订单",
  "dash.copyLink": "复制接单链接",
  "dash.capiSays": "你做得超棒！",
  "dash.stat.held": "托管中",
  "dash.stat.paid": "已到账",
  "dash.stat.requests": "新请求",
  "dash.stat.release": "平均到账时间",
  "dash.stat.releaseVal": "1.8 天",
  "dash.attention": "需要你处理",
  "dash.seeAll": "查看全部",
  "dash.earnings": "每周收入",
  "dash.activity": "最新动态",
  "act.1": "Olivia 确认了“Etsy 横幅” · 已到账 $75",
  "act.2": "Mei Lin 给你发了新请求",
  "act.3": "AI 发现 IMG_014 背景偏灰",
  "act.4": "James 已向托管支付 $150",
  "time.min": "{n} 分钟前",
  "time.hour": "{n} 小时前",
  "time.yesterday": "昨天",
  "order.due": "截止 {date}",
  "toast.copied": "链接已复制！",

  "orders.title": "订单",
  "orders.sub": "收到的和发出的订单，都在这里。",
  "orders.myPage": "我的接单页",
  "orders.new": "给客户发新订单",
  "orders.tab.from": "来自客户",
  "orders.tab.fromSub": "客户请你做的工作",
  "orders.tab.to": "发给客户",
  "orders.tab.toSub": "你发给客户的订单",
  "orders.newBadge": "{n} 个新的！",
  "filter.all": "全部",
  "filter.action": "待处理",
  "filter.escrow": "进行中",
  "filter.review": "审核中",
  "filter.paid": "已付清",
  "orders.empty": "这里还没有内容",
  "orders.emptySub": "换个筛选条件，或者发一个新订单。",
  "orders.share.t": "想接更多客户订单？",
  "orders.share.b": "把接单页分享到 Instagram、LinkedIn 或 WhatsApp。客户描述需求，AI 自动写合同。",
  "orders.share.preview": "预览",
  "cta.review": "查看",
  "cta.remind": "提醒",
  "cta.deliver": "交付",
  "cta.view": "查看",
  "cta.fix": "去修改",
  "cta.receipt": "收据",

  "new.title": "给客户发送订单",
  "new.sub": "写一次需求，Lunas 自动生成合同和 PayPal 付款链接。",
  "new.s1": "客户",
  "new.s2": "工作内容",
  "new.s3": "合同",
  "new.s4": "发送",
  "new.clientT": "这个订单发给谁？",
  "new.clientB": "我们会给对方发邮件，附上查看和付款的链接。",
  "new.clientName": "客户姓名",
  "new.clientEmail": "客户邮箱",
  "new.clientCountry": "国家",
  "new.currency": "币种",
  "new.fillDemo": "填入示例客户",
  "new.jobT": "你要交付什么？",
  "new.jobB": "像发消息一样写。记得写上数字：数量、尺寸、格式、时间。",
  "new.briefLabel": "工作描述",
  "new.briefPh": "例如：6 张 Instagram 图，1080x1350 PNG，品牌色，周五前，$120",
  "new.useExample": "使用示例",
  "new.draftAI": "用 AI 起草合同",
  "new.redraft": "重新起草",
  "new.aiHint": "AI 会把你的描述变成可检查的标准。",
  "new.thinking": "Capi 正在阅读你的需求…",
  "new.criteria": "验收标准",
  "new.aiVerified": "AI 验收",
  "new.agreement": "工作协议",
  "new.orderTitle": "订单标题",
  "new.draft": "草稿",
  "new.amount": "价格",
  "new.due": "截止日期",
  "new.window": "客户审核期",
  "new.hours": "小时",
  "new.windowHint": "如果客户 {h} 小时内没有回应，款项将自动打给你。",
  "new.addCrit": "添加自定义标准…",
  "new.clientPays": "客户支付",
  "new.fee": "Lunas 服务费（2.5%，由客户支付）",
  "new.youGet": "你将收到",
  "new.send": "创建并发送",
  "new.sentT": "订单已发送！",
  "new.sentB": "我们已给 {name} 发送邮件，对方可查看合同并用 PayPal 付款。资金锁定后会第一时间通知你。",
  "new.copy": "复制链接",
  "new.email": "再发一次邮件",
  "new.previewT": "客户看到的样子",
  "new.from": "来自",
  "new.previewProtect": "受 Lunas 托管保护 · {h} 小时审核期",
  "new.goOrder": "查看订单",
  "new.another": "再建一个",
  "pay.with": "使用",

  "tl.agree": "协议",
  "tl.fund": "已付款",
  "tl.work": "交付",
  "tl.verify": "AI 检查",
  "tl.lunas": "付清",
  "toast.accepted": "已接受！付款链接已发送。",
  "toast.funded": "资金已锁定在托管中！",
  "decl.t": "你拒绝了这个请求",
  "decl.b": "我们已礼貌地通知客户，资金未变动。",
  "decl.undo": "撤销",
  "od.briefFrom": "原始需求",
  "od.window": "审核期",
  "od.auto": "自动放款",
  "req.t": "{name} 想和你合作！",
  "req.b": "AI 已把需求整理成清晰的标准。接受，或者提出修改。",
  "req.accept": "接受 · {amount}",
  "req.counter": "提出修改",
  "req.decline": "拒绝",
  "pay.t": "等待客户付款",
  "pay.b": "我们已给 {name} 发送 PayPal 付款链接。资金锁定后再开工。",
  "pay.remind": "发送提醒",
  "demo.label": "演示 · 模拟客户操作",
  "pay.processing": "正在 PayPal 沙盒中扣款…",
  "pay.captured": "已扣款 · 已锁定",
  "pay.simulate": "客户付款，使用",
  "dl.t": "该交付啦！",
  "dl.b": "资金已锁定。上传文件，让 AI 对照合同检查。",
  "dl.verT": "AI 正在检查你的文件…",
  "dl.verB": "逐条检查，不看主观意见，只看合同。",
  "dl.revT": "快好了！还有一处要改",
  "dl.revB": "修改期间，资金仍安全锁定。",
  "dl.drop": "把文件拖到这里",
  "dl.dropSub": "或点击上传 · 演示使用示例图片",
  "dl.run": "运行 AI 检查",
  "dl.agentSays": "验收代理",
  "dl.agentMsg": "IMG_014 的背景是浅灰色（21% 非白色像素）。修改后重新上传即可，其他都很完美！",
  "dl.reupload": "重新上传修改后的文件",
  "rev.t": "全部通过！客户审核中",
  "rev.b": "{name} 现在可以确认。如果对方不回应，你也会自动收到款项。",
  "rev.until": "后自动放款",
  "rev.safe": "你的钱受保护",
  "rev.explain": "客户只能基于某条标准提出异议。不回应即视为确认。",
  "rev.simulate": "客户确认",
  "rev.releasing": "放款中…",
  "paid.t": "LUNAS！钱到账了",
  "paid.b": "{amount} 已通过 Payouts 发送到你的 PayPal。",
  "log.title": "代理动态",

  "pub.imSari": "我是 Sari →",
  "pub.bio": "来自日惹的产品修图师和设计师，让网店看起来更诱人。6 年经验，86 位满意客户，零纠纷。",
  "pub.skill1": "照片修图",
  "pub.skill2": "社交媒体设计",
  "pub.skill3": "Logo",
  "pub.skill4": "Etsy 和 Shopify",
  "pub.rating": "评分",
  "pub.done": "已完成订单",
  "pub.release": "平均交付",
  "pub.protectT": "你受 Lunas 保护",
  "pub.protectB": "你的付款保存在托管中，只有作品符合合同才会放款。",
  "pub.kicker": "订单请求",
  "pub.title": "2 分钟雇佣 {name}",
  "pub.sub": "描述你的需求，AI 会把它变成双方都信任的清晰合同。",
  "pub.yourName": "你的名字",
  "pub.yourEmail": "你的邮箱",
  "pub.briefPh": "例如：需要修 20 张产品图，白底，JPG，周五前。预算 $150。",
  "pub.budget": "预算（美元）",
  "pub.send": "发送请求",
  "pub.noPayYet": "现在不用付款。Sari 接受后，再用 PayPal 付款。",
  "pub.sentT": "请求已发送！",
  "pub.sentB": "{name} 通常几小时内回复。她接受后，我们会发邮件到 {email}。",
  "pub.next1": "Sari 查看你的请求和合同",
  "pub.next2": "你用 PayPal 支付 {amount} 到托管",
  "pub.next3": "AI 检查作品，你确认。Lunas！",
  "pub.seeAsSari": "以 Sari 的视角查看",
  "pub.another": "再发一个",
};

const id: Record<string, string> = {
  "ex.toClient": "Halo Aiko! Aku akan mendesain 6 slide Instagram untuk peluncuran studio keramikmu: 1080x1350 PNG, warna brand, dikirim sebelum Jumat. Harga $120.",
  "ex.fromClient": "Halo Sari! Aku butuh 20 foto produk diedit untuk toko online. Latar putih bersih, minimal 2000px, JPG. Bisa selesai sebelum Jumat? Budget $150.",
  "common.back": "Kembali",
  "common.next": "Lanjut",

  "nav.dashboard": "Beranda",
  "nav.orders": "Pesanan",
  "nav.newOrder": "Kirim pesanan",
  "nav.myPage": "Halaman pesananku",
  "nav.profile": "Profil",
  "theme.label": "Tema",
  "theme.candy": "Permen",
  "theme.midnight": "Tengah Malam",
  "theme.matcha": "Matcha",
  "me.menu.profile": "Lihat profil",
  "me.menu.public": "Halaman publikku",
  "me.menu.paypal": "PayPal & pencairan",
  "me.menu.signout": "Keluar",
  "me.toast.bye": "Keluar dari demo — sampai jumpa! 👋",
  "me.title": "Profilmu",
  "me.sub": "Identitas freelancer, preferensi, dan akun pembayaranmu.",
  "me.since": "Anggota sejak 2024",
  "me.langs": "Bahasa EN · ID · 中文",
  "me.edit": "Edit profil",
  "me.toast.edit": "Edit profil menyusul bersama backend asli 🙂",
  "me.stats.done": "Pesanan selesai",
  "me.stats.earned": "Total pendapatan",
  "me.stats.rating": "Rating klien",
  "me.prefs.theme": "Tema",
  "me.prefs.themeBody": "Pilih suasana — tersimpan otomatis.",
  "me.prefs.lang": "Bahasa",
  "me.prefs.langBody": "Bahasa untuk menu, tombol, dan email.",
  "me.paypal.title": "PayPal sandbox",
  "me.paypal.body": "Akun untuk escrow, pencairan, dan payout.",
  "me.paypal.connected": "Terhubung",
  "me.paypal.manage": "Kelola",
  "me.paypal.docs": "Dokumen API",
  "me.signoutCard": "Keluar dari demo ini",
  "me.signoutBody": "Bahasa dan temamu tetap tersimpan di perangkat ini.",
  "tip.title": "Tips dari Capi",
  "tip.body": "Ada {n} permintaan baru. Klien yang dibalas dalam 2 jam 3× lebih mungkin membayar!",
  "top.search": "Cari pesanan, klien…",
  "top.notifications": "Notifikasi",

  "status.request": "Permintaan baru",
  "status.awaiting_payment": "Menunggu pembayaran",
  "status.in_escrow": "Dana terkunci · dikerjakan",
  "status.verifying": "AI sedang mengecek",
  "status.revision": "Perlu diperbaiki",
  "status.review": "Klien sedang meninjau",
  "status.paid": "Lunas!",
  "status.declined": "Ditolak",

  "rail.paid": "{amount} sudah masuk ke PayPal {name} 🎉",
  "rail.held": "{amount} terkunci aman di escrow",
  "rail.declined": "Pesanan ditolak · tidak ada uang berpindah",
  "rail.notFunded": "Belum dibayar · tidak ada risiko",
  "rail.client": "Klien",
  "rail.escrow": "Escrow Lunas",
  "rail.you": "Kamu",
  "stamp.sub": "SUDAH DIBAYAR",

  "lp.nav.how": "Cara kerja",
  "lp.nav.who": "Untuk siapa",
  "lp.nav.try": "Coba stempelnya",
  "lp.openApp": "Buka aplikasi",
  "lp.kicker": "Escrow PayPal + AI untuk freelancer",
  "lp.h1.a": "Dibayar klien luar negeri,",
  "lp.h1.b": "tanpa was-was",
  "lp.h1.c": "dan langsung dicap.",
  "lp.sub": "Lunas mengubah brief yang berantakan jadi kontrak yang jelas, mengunci uangnya lewat PayPal, lalu AI mengecek hasil kerjamu. Kalau semua beres, tinggal cap LUNAS.",
  "lp.cta1": "Kirim pesanan pertamamu",
  "lp.cta2": "Lihat tampilan klien",
  "lp.trust1": "Aman dengan PayPal",
  "lp.trust2": "Hasil kerja dicek AI",
  "lp.trust3": "EN · 中文 · ID",
  "lp.scene.contract": "Perjanjian kerja",
  "lp.scene.job": "20 foto produk",
  "lp.scene.c1": "Tepat 20 file",
  "lp.scene.c2": "Format JPG",
  "lp.scene.c3": "Min. 2000px",
  "lp.scene.c4": "Latar putih",
  "lp.scene.passed": "lolos",

  "how.kicker": "4 langkah mungil",
  "how.title": "Cara kerja Lunas",
  "how.1.t": "Ceritakan",
  "how.1.b": "Tulis pekerjaannya seperti chat biasa. AI mengubahnya jadi syarat yang bisa dicek: jumlah file, ukuran, format, tenggat.",
  "how.2.t": "Kunci uangnya",
  "how.2.b": "Klien bayar lewat PayPal. Uang menunggu aman di escrow, nggak ada yang bisa kabur.",
  "how.3.t": "AI cek hasilnya",
  "how.3.b": "Upload hasil kerja. Agen AI mengecek setiap syarat dan minta revisi sebelum ada yang ribut.",
  "how.4.t": "Lunas!",
  "how.4.b": "Klien setuju (atau diam 72 jam), uang langsung masuk PayPal-mu. Cap!",

  "who.f.k": "Untuk freelancer",
  "who.f.t": "Nggak perlu nagih-nagih lagi",
  "who.f.1": "Tetap dibayar walau klien menghilang",
  "who.f.2": "Bye-bye revisi “dikit lagi ya…” tanpa akhir",
  "who.f.3": "Halaman pesanan sendiri, bisa dibagikan di mana saja",
  "who.f.4": "Bisa dengan klien dari negara mana pun",
  "who.c.k": "Untuk klien",
  "who.c.t": "Bayar di muka tanpa rasa takut",
  "who.c.1": "Uang baru cair kalau hasilnya sesuai",
  "who.c.2": "Syarat yang jelas, ditulis oleh AI",
  "who.c.3": "Bayar pakai akun PayPal atau kartu",
  "who.c.4": "Refund adil dan cepat kalau ada masalah",

  "try.kicker": "Ayo, pencet",
  "try.title": "Tombol paling memuaskan di dunia fintech",
  "try.body": "Di Indonesia, toko mencap nota “LUNAS” kalau sudah dibayar penuh. Tradisi itu kami bawa ke dunia digital.",
  "try.button": "Cap sekarang!",
  "try.again": "Cap lagi",
  "try.receipt": "Bukti pembayaran",
  "try.r.to": "Dibayar ke",
  "try.r.from": "Dibayar oleh",
  "try.r.check": "Verifikasi",
  "try.meaning": "“Lunas” artinya sudah dibayar penuh. Ya, sesimpel itu.",
  "cta.title": "Siap dibayar dengan benar?",
  "cta.body": "Gratis di sandbox. Cuma 2 menit. Capi sudah menunggu.",
  "foot.note": "Dibuat untuk PayPal AI Hackathon · berjalan di PayPal sandbox",

  "dash.hi": "Selamat pagi, {name}!",
  "dash.summary": "Ada {r} permintaan baru dan {w} pesanan yang menunggumu. Yuk, mulai ngecap!",
  "dash.sendOrder": "Kirim pesanan ke klien",
  "dash.copyLink": "Salin link pesananku",
  "dash.capiSays": "Kamu keren banget!",
  "dash.stat.held": "Di escrow",
  "dash.stat.paid": "Sudah cair",
  "dash.stat.requests": "Permintaan baru",
  "dash.stat.release": "Rata-rata pencairan",
  "dash.stat.releaseVal": "1,8 hari",
  "dash.attention": "Perlu kamu tangani",
  "dash.seeAll": "Lihat semua",
  "dash.earnings": "Penghasilan mingguan",
  "dash.activity": "Aktivitas terbaru",
  "act.1": "Olivia menyetujui “Etsy banner” · $75 cair",
  "act.2": "Mei Lin mengirim permintaan baru",
  "act.3": "AI menemukan latar abu-abu di IMG_014",
  "act.4": "James menyetor $150 ke escrow",
  "time.min": "{n} menit lalu",
  "time.hour": "{n} jam lalu",
  "time.yesterday": "Kemarin",
  "order.due": "Tenggat {date}",
  "toast.copied": "Link disalin!",

  "orders.title": "Pesanan",
  "orders.sub": "Semua pesanan masuk dan keluar, di satu tempat yang ceria.",
  "orders.myPage": "Halaman pesananku",
  "orders.new": "Pesanan baru ke klien",
  "orders.tab.from": "Dari klien",
  "orders.tab.fromSub": "Klien memintamu mengerjakan sesuatu",
  "orders.tab.to": "Ke klien",
  "orders.tab.toSub": "Pesanan yang kamu kirim ke klien",
  "orders.newBadge": "{n} baru!",
  "filter.all": "Semua",
  "filter.action": "Perlu tindakan",
  "filter.escrow": "Berjalan",
  "filter.review": "Ditinjau",
  "filter.paid": "Lunas",
  "orders.empty": "Belum ada apa-apa di sini",
  "orders.emptySub": "Coba filter lain, atau kirim pesanan baru.",
  "orders.share.t": "Mau lebih banyak pesanan dari klien?",
  "orders.share.b": "Bagikan halaman pesananmu di Instagram, LinkedIn, atau WhatsApp. Klien cukup menulis kebutuhannya, AI yang membuat kontraknya.",
  "orders.share.preview": "Pratinjau",
  "cta.review": "Tinjau",
  "cta.remind": "Ingatkan",
  "cta.deliver": "Kirim hasil",
  "cta.view": "Lihat",
  "cta.fix": "Perbaiki",
  "cta.receipt": "Bukti",

  "new.title": "Kirim pesanan ke klien",
  "new.sub": "Tulis pekerjaannya sekali. Lunas membuatkan kontrak dan link pembayaran PayPal.",
  "new.s1": "Klien",
  "new.s2": "Pekerjaan",
  "new.s3": "Kontrak",
  "new.s4": "Kirim",
  "new.clientT": "Pesanan ini untuk siapa?",
  "new.clientB": "Kami akan mengirim email berisi link untuk meninjau dan membayar.",
  "new.clientName": "Nama klien",
  "new.clientEmail": "Email klien",
  "new.clientCountry": "Negara",
  "new.currency": "Mata uang",
  "new.fillDemo": "Isi klien contoh",
  "new.jobT": "Apa yang akan kamu kirim?",
  "new.jobB": "Tulis seperti chat. Sertakan angka: berapa banyak, ukuran, format, kapan.",
  "new.briefLabel": "Deskripsi pekerjaan",
  "new.briefPh": "mis. 6 slide Instagram, 1080x1350 PNG, warna brand, sebelum Jumat, $120",
  "new.useExample": "Pakai contoh",
  "new.draftAI": "Buat kontrak dengan AI",
  "new.redraft": "Buat ulang",
  "new.aiHint": "AI mengubah kata-katamu jadi syarat yang bisa dicek.",
  "new.thinking": "Capi sedang membaca brief-mu…",
  "new.criteria": "Syarat penerimaan",
  "new.aiVerified": "Dicek AI",
  "new.agreement": "Perjanjian kerja",
  "new.orderTitle": "Judul pesanan",
  "new.draft": "Draf",
  "new.amount": "Harga",
  "new.due": "Tenggat",
  "new.window": "Waktu tinjau klien",
  "new.hours": "jam",
  "new.windowHint": "Kalau klien tidak merespons dalam {h} jam, uang otomatis cair ke kamu.",
  "new.addCrit": "Tambah syarat sendiri…",
  "new.clientPays": "Klien membayar",
  "new.fee": "Biaya Lunas (2,5%, dibayar klien)",
  "new.youGet": "Kamu terima",
  "new.send": "Buat & kirim",
  "new.sentT": "Pesanan terkirim!",
  "new.sentB": "Kami sudah mengirim email ke {name} berisi link untuk meninjau kontrak dan membayar lewat PayPal. Kamu akan dikabari begitu uangnya terkunci.",
  "new.copy": "Salin link",
  "new.email": "Kirim email lagi",
  "new.previewT": "Yang dilihat klienmu",
  "new.from": "Dari",
  "new.previewProtect": "Dilindungi escrow Lunas · tinjau {h} jam",
  "new.goOrder": "Lihat pesanan",
  "new.another": "Buat lagi",
  "pay.with": "Bayar dengan",

  "tl.agree": "Perjanjian",
  "tl.fund": "Dibayar",
  "tl.work": "Pengiriman",
  "tl.verify": "Cek AI",
  "tl.lunas": "Lunas",
  "toast.accepted": "Diterima! Link pembayaran terkirim.",
  "toast.funded": "Uang terkunci di escrow!",
  "decl.t": "Kamu menolak permintaan ini",
  "decl.b": "Klien sudah diberi tahu dengan sopan. Tidak ada uang berpindah.",
  "decl.undo": "Batalkan",
  "od.briefFrom": "brief asli",
  "od.window": "Waktu tinjau",
  "od.auto": "cair otomatis",
  "req.t": "{name} ingin bekerja sama denganmu!",
  "req.b": "AI sudah mengubah brief-nya jadi syarat yang jelas. Terima, atau usulkan perubahan.",
  "req.accept": "Terima · {amount}",
  "req.counter": "Usulkan perubahan",
  "req.decline": "Tolak",
  "pay.t": "Menunggu klien membayar",
  "pay.b": "Link pembayaran PayPal sudah dikirim ke {name}. Mulai kerja setelah uangnya terkunci.",
  "pay.remind": "Kirim pengingat",
  "demo.label": "Demo · simulasi klien",
  "pay.processing": "Memproses di PayPal sandbox…",
  "pay.captured": "Berhasil · terkunci",
  "pay.simulate": "Klien bayar dengan",
  "dl.t": "Waktunya kirim hasil!",
  "dl.b": "Uang sudah terkunci. Upload file-mu dan biarkan AI mengeceknya sesuai kontrak.",
  "dl.verT": "AI sedang mengecek file-mu…",
  "dl.verB": "Satu per satu, sesuai kontrak. Bukan soal selera.",
  "dl.revT": "Dikit lagi! Ada satu yang perlu diperbaiki",
  "dl.revB": "Uang tetap terkunci aman selama kamu memperbaikinya.",
  "dl.drop": "Taruh file-mu di sini",
  "dl.dropSub": "atau klik untuk upload · demo memakai gambar contoh",
  "dl.run": "Jalankan cek AI",
  "dl.agentSays": "Agen verifikasi",
  "dl.agentMsg": "IMG_014 latarnya abu-abu muda (21% piksel tidak putih). Perbaiki lalu upload ulang. Sisanya sudah sempurna!",
  "dl.reupload": "Upload ulang file yang sudah diperbaiki",
  "rev.t": "Semua lolos! Klien sedang meninjau",
  "rev.b": "{name} bisa menyetujui sekarang. Kalau diam saja, kamu tetap dibayar otomatis.",
  "rev.until": "sampai cair otomatis",
  "rev.safe": "Uangmu terlindungi",
  "rev.explain": "Klien hanya bisa komplain dengan alasan yang terkait syarat di kontrak. Diam berarti setuju.",
  "rev.simulate": "Klien menyetujui",
  "rev.releasing": "Mencairkan…",
  "paid.t": "LUNAS! Kamu sudah dibayar",
  "paid.b": "{amount} dikirim ke PayPal-mu lewat Payouts.",
  "log.title": "Aktivitas agen",

  "pub.imSari": "Aku Sari →",
  "pub.bio": "Editor foto produk & desainer dari Yogyakarta. Bikin toko online kelihatan menggoda. 6 tahun, 86 klien puas, nol drama.",
  "pub.skill1": "Edit foto",
  "pub.skill2": "Desain media sosial",
  "pub.skill3": "Logo",
  "pub.skill4": "Etsy & Shopify",
  "pub.rating": "rating",
  "pub.done": "pesanan selesai",
  "pub.release": "rata-rata kirim",
  "pub.protectT": "Kamu dilindungi Lunas",
  "pub.protectB": "Pembayaranmu ditahan di escrow dan baru cair kalau hasilnya sesuai kontrak.",
  "pub.kicker": "Permintaan pesanan",
  "pub.title": "Pesan jasa {name} dalam 2 menit",
  "pub.sub": "Ceritakan kebutuhanmu. AI mengubahnya jadi kontrak jelas yang dipercaya kedua pihak.",
  "pub.yourName": "Nama kamu",
  "pub.yourEmail": "Email kamu",
  "pub.briefPh": "mis. Saya butuh 20 foto produk diedit, latar putih, JPG, sebelum Jumat. Budget $150.",
  "pub.budget": "Budget (USD)",
  "pub.send": "Kirim permintaan",
  "pub.noPayYet": "Belum perlu bayar apa pun. Kamu baru bayar lewat PayPal setelah Sari menerima.",
  "pub.sentT": "Permintaan terkirim!",
  "pub.sentB": "{name} biasanya membalas dalam beberapa jam. Kami akan mengirim email ke {email} begitu dia menerima.",
  "pub.next1": "Sari meninjau permintaan & kontrakmu",
  "pub.next2": "Kamu bayar {amount} lewat PayPal ke escrow",
  "pub.next3": "AI mengecek hasilnya, lalu kamu setujui. Lunas!",
  "pub.seeAsSari": "Lihat sebagai Sari",
  "pub.another": "Kirim lagi",
};

export const dict: Record<Lang, Record<string, string>> = { en, zh, id };
